export const API_COLLECTIONS_TEXT = {
  TITLE: 'API Collections & Endpoints',
  SUBTITLE: 'Define mock endpoint contracts and route parameters',
  ADD_COLLECTION_BTN: 'Add API Collection',
  SEARCH_PLACEHOLDER: 'Search endpoint name or path...',
  NO_ENDPOINTS: 'No API collections found',
  ACTION_VIEW_CONFIG: 'View Config',
  ACTION_EDIT: 'Edit Endpoint',
  ACTION_DUPLICATE: 'Duplicate',
  ACTION_DELETE: 'Delete Endpoint',
  ALL_METHODS: 'All Methods',
  ALL_STATUS: 'All Status',
  ACTIVE: 'Active',
  DISABLED: 'Disabled',
  MODAL_ADD_TITLE: 'Add API Collection',
  MODAL_EDIT_TITLE: 'Edit API Collection',
  LABEL_NAME: 'Name / Label *',
  LABEL_METHOD: 'Method *',
  LABEL_PATH: 'Path / Route *',
  LABEL_DESCRIPTION: 'Description',
  LABEL_ACTIVE_STATUS: 'Active Status',
  PLACEHOLDER_NAME: 'e.g. Get User Profile',
  PLACEHOLDER_PATH: '/api/v1/users/:id',
  PLACEHOLDER_DESC: 'Optional notes or documentation...',
  BTN_CANCEL: 'Cancel',
  BTN_CREATE: 'Create Endpoint',
  BTN_SAVE: 'Save Changes',
  DELETE_DIALOG_TITLE: 'Delete API Endpoint?',
  DELETE_DIALOG_DESC: 'Are you sure you want to delete this API endpoint? All associated request and response scenarios will be deleted.',
  DELETE_DIALOG_CONFIRM: 'Delete',
  MODAL_CREATE_COLLECTION_TITLE: 'Create Collection',
  MODAL_EDIT_COLLECTION_TITLE: 'Edit Collection',
  PLACEHOLDER_COLLECTION_NAME: 'e.g. Users, Checkout, Admin Panel',
  PLACEHOLDER_COLLECTION_DESC: 'Optional description of the endpoints in this folder',
  ENDPOINTS_COUNT_SUFFIX: 'endpoints',
  DEFAULT_COLLECTION_TAG: 'Default Collection',
  CREATE_FOLDER_BTN: 'Create Folder',
  NO_MATCHING_ENDPOINTS: (search: string) => `No API endpoint definitions matching "${search}"`,
  NO_ENDPOINTS_DESC: 'Add an API Collection endpoint or create a Folder to organize your project endpoints.',
  TITLE_EDIT_FOLDER: 'Edit Folder',
  TITLE_DELETE_FOLDER: 'Delete Folder',
  EMPTY_FOLDER_NOTICE: 'Empty Folder. Edit an endpoint to add it here.',
  UNGROUPED_ENDPOINTS: 'Ungrouped Endpoints',
  DELETE_FOLDER_DIALOG_TITLE: 'Delete Folder',
  DELETE_FOLDER_DIALOG_DESC: 'Are you sure you want to delete this folder? The APIs inside will not be deleted, but will become ungrouped.',
  LABEL_FOLDER_COLLECTION_OPTIONAL: 'Folder / Collection (Optional)',
  NO_COLLECTION_UNGROUPED: 'No Collection (Ungrouped)',
  LABEL_PIC_OPTIONAL: 'Person In Charge (PIC) - Optional',
  PLACEHOLDER_PIC_SELECT: 'Pilih PIC endpoint...',
} as const;

