export const API_COLLECTIONS_SEMANTIC_ID = {
  CONTAINER: 'api-collections-container',
  HEADER: 'api-collections-header',
  FILTER_BAR: 'api-collections-filter-bar',
  SEARCH_INPUT: 'api-collections-search-input',
  ADD_BTN: 'api-collections-add-btn',
  ADD_FOLDER_BTN: 'api-collections-add-folder-btn',
  METHOD_FILTER_SELECT: 'api-collections-method-filter-select',
  STATUS_FILTER_SELECT: 'api-collections-status-filter-select',
  LIST: 'api-collections-list',
  FOLDER_ITEM: (id: string) => `api-collections-folder-${id}`,
  FOLDER_TOGGLE_BTN: (id: string) => `api-collections-folder-toggle-${id}`,
  FOLDER_EDIT_BTN: (id: string) => `api-collections-folder-edit-${id}`,
  FOLDER_DELETE_BTN: (id: string) => `api-collections-folder-delete-${id}`,
  ITEM_ROW: (id: string) => `api-collection-item-${id}`,
  ITEM_NAVIGATE_BTN: (id: string) => `api-collection-item-navigate-${id}`,
  ITEM_DROPDOWN_TRIGGER: (id: string) => `api-collection-item-dropdown-trigger-${id}`,
  ITEM_ACTION_EDIT: (id: string) => `api-collection-item-action-edit-${id}`,
  ITEM_ACTION_DUPLICATE: (id: string) => `api-collection-item-action-duplicate-${id}`,
  ITEM_ACTION_DELETE: (id: string) => `api-collection-item-action-delete-${id}`,
  FORM_MODAL: 'api-collections-form-modal',
  FORM_CLOSE_BTN: 'api-collections-form-close-btn',
  FORM_INPUT_NAME: 'api-collections-form-input-name',
  FORM_SELECT_COLLECTION: 'api-collections-form-select-collection',
  FORM_SELECT_METHOD: 'api-collections-form-select-method',
  FORM_INPUT_PATH: 'api-collections-form-input-path',
  FORM_TEXTAREA_DESC: 'api-collections-form-textarea-desc',
  FORM_CHECKBOX_STATUS: 'api-collections-form-checkbox-status',
  FORM_FOOTER: 'api-collections-form-footer',
  FORM_BTN_SUBMIT: 'api-collections-form-btn-submit',
  FORM_BTN_CANCEL: 'api-collections-form-btn-cancel',
  FOLDER_MODAL: 'api-collections-folder-modal',
  FOLDER_MODAL_CLOSE_BTN: 'api-collections-folder-modal-close-btn',
  FOLDER_MODAL_INPUT_NAME: 'api-collections-folder-modal-input-name',
  FOLDER_MODAL_TEXTAREA_DESC: 'api-collections-folder-modal-textarea-desc',
  FOLDER_MODAL_BTN_CANCEL: 'api-collections-folder-modal-btn-cancel',
  FOLDER_MODAL_BTN_SUBMIT: 'api-collections-folder-modal-btn-submit',
} as const;

