export const SCENARIO_FLOWS_SEMANTIC_ID = {
  CONTAINER: 'scenario-flows-container',
  HEADER: 'scenario-flows-header',
  TITLE: 'scenario-flows-title',
  SEARCH_INPUT: 'scenario-flows-search-input',
  PROJECT_FILTER: 'scenario-flows-project-filter',
  IMPORT_BTN: 'scenario-flows-import-btn',
  CREATE_BTN: 'scenario-flows-create-btn',
  FLOWS_GRID: 'scenario-flows-grid',
  EMPTY_STATE: 'scenario-flows-empty-state',
  EMPTY_CREATE_BTN: 'scenario-flows-empty-create-btn',
  EMPTY_IMPORT_BTN: 'scenario-flows-empty-import-btn',
  FLOW_CARD_PREFIX: (id: string) => `scenario-flow-card-${id}`,
  FLOW_RUN_BTN_PREFIX: (id: string) => `scenario-flow-run-btn-${id}`,
  FLOW_EDIT_BTN_PREFIX: (id: string) => `scenario-flow-edit-btn-${id}`,
  FLOW_DELETE_BTN_PREFIX: (id: string) => `scenario-flow-delete-btn-${id}`,
  FLOW_EXPORT_BTN_PREFIX: (id: string) => `scenario-flow-export-btn-${id}`,
  FLOW_BUILDER_LINK_PREFIX: (id: string) => `scenario-flow-builder-link-${id}`,
  MODAL_CREATE: 'scenario-flows-modal-create',
  MODAL_CREATE_INPUT_NAME: 'scenario-flows-create-input-name',
  MODAL_CREATE_SELECT_PROJECT: 'scenario-flows-create-select-project',
  MODAL_CREATE_INPUT_DESC: 'scenario-flows-create-input-desc',
  MODAL_CREATE_SELECT_ENV: 'scenario-flows-create-select-env',
  MODAL_CREATE_SWITCH_STOP: 'scenario-flows-create-switch-stop',
  MODAL_CREATE_TEXTAREA_VARS: 'scenario-flows-create-textarea-vars',
  MODAL_CREATE_BTN_SUBMIT: 'scenario-flows-create-btn-submit',
  MODAL_CREATE_BTN_CANCEL: 'scenario-flows-create-btn-cancel',
  MODAL_IMPORT: 'scenario-flows-modal-import',
  MODAL_IMPORT_SELECT_PROJECT: 'scenario-flows-import-select-project',
  MODAL_IMPORT_FILE_INPUT: 'scenario-flows-import-file-input',
  MODAL_IMPORT_TEXTAREA_JSON: 'scenario-flows-import-textarea-json',
  MODAL_IMPORT_SAMPLE_BTN: 'scenario-flows-import-sample-btn',
  MODAL_IMPORT_BTN_SUBMIT: 'scenario-flows-import-btn-submit',
  MODAL_IMPORT_BTN_CANCEL: 'scenario-flows-import-btn-cancel',
} as const;
