export const SCENARIO_FLOWS_TEXT = {
  TITLE: 'Scenario Flow Chaining',
  SUBTITLE: 'Build, chain, and run automated end-to-end API test flows with dynamic data passing and real-time execution.',
  CREATE_BTN: 'New Flow',
  IMPORT_BTN: 'Import Flow JSON',
  SEARCH_PLACEHOLDER: 'Search scenario flows by name or description...',
  FILTER_PROJECT_LABEL: 'Filter Project:',
  ALL_PROJECTS: 'All Projects',
  CROSS_PROJECT_FLOWS: 'Cross-Project Flows',
  EMPTY_TITLE: 'No Scenario Flows Yet',
  EMPTY_DESC: 'Create a flow manually or import an existing JSON template to start chaining APIs.',
  LOADING: 'Loading scenario flows...',
  CREATE_MANUALLY: 'Create Manually',
  IMPORT_TEMPLATE_JSON: 'Import Template JSON',
  RUN_NOW: 'Run Testing',
  RUNNING: 'Running...',
  EDIT: 'Edit Flow',
  DELETE: 'Delete Flow',
  EXPORT_JSON: 'Export JSON',
  STEPS_COUNT: 'steps',
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'Draft',
  LAST_RUN: 'Last Run',
  NO_RUNS_YET: 'Never run',
  CROSS_PROJECT_BADGE: 'Cross-Project',
  SUCCESS_BADGE: 'Success',
  FAILED_BADGE: 'Failed',
  CONFIRM_DELETE_TITLE: 'Delete Scenario Flow',
  CONFIRM_DELETE_DESC: (name: string) => `Are you sure you want to delete "${name}"? This action cannot be undone.`,
  DELETE_BTN: 'Delete',
  CANCEL_BTN: 'Cancel',

  // Create Flow Modal
  CREATE_MODAL_TITLE: 'Create Scenario Flow',
  CREATE_MODAL_SUBTITLE: 'Build multi-step automated API chains and testing pipelines',
  MODAL_CREATE_NAME_LABEL: 'Flow Name',
  MODAL_CREATE_NAME_PLACEHOLDER: 'e.g., Checkout & Payment Validation Flow',
  MODAL_CREATE_PROJECT_LABEL: 'Project',
  MODAL_CREATE_PROJECT_GLOBAL: 'Global (All Projects)',
  MODAL_CREATE_DESC_LABEL: 'Description',
  MODAL_CREATE_DESC_PLACEHOLDER: 'Optional description about this flow...',
  MODAL_CREATE_ENV_LABEL: 'Default Execution Environment',
  MODAL_CREATE_ENV_NONE: 'No Default (Select during run)',
  MODAL_CREATE_STOP_ON_FAILURE_LABEL: 'Stop execution on first step failure',
  MODAL_CREATE_STOP_ON_FAILURE_DESC: 'When enabled, the scenario pipeline terminates immediately if any step fails.',
  MODAL_CREATE_VARS_LABEL: 'Flow Variables (JSON)',
  MODAL_CREATE_VARS_ERROR: 'Invalid JSON format for variables',
  MODAL_CREATE_SUBMIT_BTN: 'Create Flow',
  MODAL_CREATE_SUBMITTING_BTN: 'Creating...',

  // Import Flow Modal
  IMPORT_MODAL_TITLE: 'Import Scenario Flow',
  IMPORT_MODAL_SUBTITLE: 'Import JSON template with intelligent Upsert',
  MODAL_IMPORT_UPSERT_ENGINE: 'Smart Upsert Engine',
  MODAL_IMPORT_UPSERT_DESC: "If the template contains APIs or Request/Response Scenarios that don't exist yet in the target project, they will be automatically generated and linked!",
  MODAL_IMPORT_PROJECT_LABEL: 'Target Project for APIs',
  MODAL_IMPORT_PROJECT_PLACEHOLDER: 'Choose a project...',
  MODAL_IMPORT_FILE_LABEL: 'Select JSON File from Computer',
  MODAL_IMPORT_BROWSE_TEXT: 'Click to browse',
  MODAL_IMPORT_FORMAT_HINT: 'Format: Exported .json from Mock API Studio',
  MODAL_IMPORT_OR_PASTE: 'OR PASTE JSON DIRECTLY',
  MODAL_IMPORT_SAMPLE_BTN: 'Insert Sample Template',
  MODAL_IMPORT_CLICK_UPLOAD: 'Click to upload JSON file',
  MODAL_IMPORT_OR_PASTE_HINT: 'or paste content below',
  MODAL_IMPORT_SELECTED_PREFIX: 'Selected: ',
  MODAL_IMPORT_TEMPLATE_LABEL: 'Template JSON',
  MODAL_IMPORT_TEMPLATE_PLACEHOLDER: 'Paste scenario flow template JSON here...',
  MODAL_IMPORT_TARGET_PROJECT_PLACEHOLDER: '-- Select Target Project --',
  MODAL_IMPORT_SUBMIT_BTN: 'Import & Upsert',
  MODAL_IMPORT_SUBMITTING_BTN: 'Importing & Upserting...',
  MODAL_IMPORT_ERR_INVALID_FILE: 'The selected file contains invalid JSON.',
  MODAL_IMPORT_ERR_SELECT_PROJECT: 'Please select a target project for imported APIs and Scenarios.',
  MODAL_IMPORT_ERR_EMPTY_JSON: 'Please provide or upload a JSON template.',
  MODAL_IMPORT_ERR_SYNTAX: 'Invalid JSON syntax. Please check the JSON format.',
  MODAL_IMPORT_ERR_FAILED: 'Failed to import scenario flow.',

  // Card
  CARD_NO_DESC: 'No description provided.',
  CARD_OPEN_BUILDER: 'Open Builder',
  CARD_RUN_TEST: 'Run Test',
} as const;
