export const SCENARIO_FLOWS_TEXT = {
  TITLE: 'Scenario Flow Chaining',
  SUBTITLE: 'Build, chain, and run automated end-to-end API test flows with dynamic data passing and real-time execution.',
  CREATE_BTN: 'New Flow',
  IMPORT_BTN: 'Import Flow JSON',
  SEARCH_PLACEHOLDER: 'Search scenario flows by name or description...',
  FILTER_PROJECT_LABEL: 'Filter Project:',
  ALL_PROJECTS: 'All Projects',
  CROSS_PROJECT_FLOWS: 'Cross-Project Flows',
  EMPTY_TITLE: 'No Scenario Flows Yet',
  EMPTY_DESC: 'Create a flow manually or import an existing JSON template to start chaining APIs.',
  RUN_NOW: 'Run Testing',
  RUNNING: 'Running...',
  EDIT: 'Edit Flow',
  DELETE: 'Delete Flow',
  EXPORT_JSON: 'Export JSON',
  STEPS_COUNT: 'steps',
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'Draft',
  LAST_RUN: 'Last Run',
  NO_RUNS_YET: 'Never run',
  CROSS_PROJECT_BADGE: 'Cross-Project',
  SUCCESS_BADGE: 'Success',
  FAILED_BADGE: 'Failed',
  CONFIRM_DELETE_TITLE: 'Delete Scenario Flow',
  CONFIRM_DELETE_DESC: (name: string) => `Are you sure you want to delete "${name}"? This action cannot be undone.`,
  DELETE_BTN: 'Delete',
  CANCEL_BTN: 'Cancel',
  IMPORT_MODAL_TITLE: 'Import Scenario Flow Template',
  IMPORT_MODAL_SUBTITLE: 'Upload or paste an exported Scenario Flow JSON file to replicate tests and APIs.',
  CREATE_MODAL_TITLE: 'Create New Scenario Flow',
  CREATE_MODAL_SUBTITLE: 'Start with an empty flow canvas or sequence to chain and orchestrate APIs.',
} as const;
