export const SCENARIO_FLOWS_TEXT = {
  TITLE: 'Scenario Flow Chaining',
  SUBTITLE: 'Build, chain, and run automated end-to-end API test flows with dynamic data passing and real-time execution.',
  CREATE_BTN: 'New Flow',
  IMPORT_BTN: 'Import Flow JSON',
  SEARCH_PLACEHOLDER: 'Search scenario flows by name or description...',
  FILTER_PROJECT_LABEL: 'Filter Project:',
  ALL_PROJECTS: 'All Projects',
  CROSS_PROJECT_FLOWS: 'Cross-Project Flows',
  EMPTY_TITLE: 'No Scenario Flows Yet',
  EMPTY_DESC: 'Create a flow manually or import an existing JSON template to start chaining APIs.',
  LOADING: 'Loading scenario flows...',
  CREATE_MANUALLY: 'Create Manually',
  IMPORT_TEMPLATE_JSON: 'Import Template JSON',
  RUN_NOW: 'Run Testing',
  RUNNING: 'Running...',
  EDIT: 'Edit Flow',
  DELETE: 'Delete Flow',
  EXPORT_JSON: 'Export JSON',
  STEPS_COUNT: 'steps',
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'Draft',
  LAST_RUN: 'Last Run',
  NO_RUNS_YET: 'Never run',
  CROSS_PROJECT_BADGE: 'Cross-Project',
  SUCCESS_BADGE: 'Success',
  FAILED_BADGE: 'Failed',
  CONFIRM_DELETE_TITLE: 'Delete Scenario Flow',
  CONFIRM_DELETE_DESC: (name: string) => `Are you sure you want to delete "${name}"? This action cannot be undone.`,
  DELETE_BTN: 'Delete',
  CANCEL_BTN: 'Cancel',

  // Create Flow Modal
  CREATE_MODAL_TITLE: 'Create Scenario Flow',
  CREATE_MODAL_SUBTITLE: 'Build multi-step automated API chains and testing pipelines',
  MODAL_CREATE_NAME_LABEL: 'Flow Name',
  MODAL_CREATE_NAME_PLACEHOLDER: 'e.g., Checkout & Payment Validation Flow',
  MODAL_CREATE_PROJECT_LABEL: 'Project',
  MODAL_CREATE_PROJECT_GLOBAL: 'Global (All Projects)',
  MODAL_CREATE_DESC_LABEL: 'Description',
  MODAL_CREATE_DESC_PLACEHOLDER: 'Optional description about this flow...',
  MODAL_CREATE_ENV_LABEL: 'Default Execution Environment',
  MODAL_CREATE_ENV_NONE: 'No Default (Select during run)',
  MODAL_CREATE_STOP_ON_FAILURE_LABEL: 'Stop execution on first step failure',
  MODAL_CREATE_STOP_ON_FAILURE_DESC: 'When enabled, the scenario pipeline terminates immediately if any step fails.',
  MODAL_CREATE_VARS_LABEL: 'Flow Variables (JSON)',
  MODAL_CREATE_VARS_ERROR: 'Invalid JSON format for variables',
  MODAL_CREATE_SUBMIT_BTN: 'Create Flow',
  MODAL_CREATE_SUBMITTING_BTN: 'Creating...',

  // Import Flow Modal
  IMPORT_MODAL_TITLE: 'Import Scenario Flow',
  IMPORT_MODAL_SUBTITLE: 'Import JSON template with intelligent Upsert',
  MODAL_IMPORT_UPSERT_ENGINE: 'Smart Upsert Engine',
  MODAL_IMPORT_UPSERT_DESC: "If the template contains APIs or Request/Response Scenarios that don't exist yet in the target project, they will be automatically generated and linked!",
  MODAL_IMPORT_PROJECT_LABEL: 'Target Project for APIs',
  MODAL_IMPORT_PROJECT_PLACEHOLDER: 'Choose a project...',
  MODAL_IMPORT_FILE_LABEL: 'Select JSON File from Computer',
  MODAL_IMPORT_BROWSE_TEXT: 'Click to browse',
  MODAL_IMPORT_FORMAT_HINT: 'Format: Exported .json from Mock API Studio',
  MODAL_IMPORT_OR_PASTE: 'OR PASTE JSON DIRECTLY',
  MODAL_IMPORT_SAMPLE_BTN: 'Insert Sample Template',
  MODAL_IMPORT_CLICK_UPLOAD: 'Click to upload JSON file',
  MODAL_IMPORT_OR_PASTE_HINT: 'or paste content below',
  MODAL_IMPORT_SELECTED_PREFIX: 'Selected: ',
  MODAL_IMPORT_TEMPLATE_LABEL: 'Template JSON',
  MODAL_IMPORT_TEMPLATE_PLACEHOLDER: 'Paste scenario flow template JSON here...',
  MODAL_IMPORT_TARGET_PROJECT_PLACEHOLDER: '-- Select Target Project --',
  MODAL_IMPORT_SUBMIT_BTN: 'Import & Upsert',
  MODAL_IMPORT_SUBMITTING_BTN: 'Importing & Upserting...',
  MODAL_IMPORT_ERR_INVALID_FILE: 'The selected file contains invalid JSON.',
  MODAL_IMPORT_ERR_SELECT_PROJECT: 'Please select a target project for imported APIs and Scenarios.',
  MODAL_IMPORT_ERR_EMPTY_JSON: 'Please provide or upload a JSON template.',
  MODAL_IMPORT_ERR_SYNTAX: 'Invalid JSON syntax. Please check the JSON format.',
  MODAL_IMPORT_ERR_FAILED: 'Failed to import scenario flow.',

  // Import Dropdown Options
  IMPORT_DROPDOWN_JSON_TITLE: 'Flow Template JSON',
  IMPORT_DROPDOWN_JSON_DESC: 'Import native Mock API Studio flow format (.json)',
  IMPORT_DROPDOWN_INSOMNIA_TITLE: 'Insomnia Collection (YAML / JSON)',
  IMPORT_DROPDOWN_INSOMNIA_DESC: 'Convert Insomnia collection v5 with response chaining (.yaml, .json)',

  // Import Insomnia Modal
  INSOMNIA_MODAL_TITLE: 'Import Insomnia Collection',
  INSOMNIA_MODAL_SUBTITLE: 'Convert Insomnia v5 Collection (YAML / JSON) with response chaining into Scenario Flow',
  MODAL_INSOMNIA_CLICK_UPLOAD: 'Click to upload Insomnia export file',
  MODAL_INSOMNIA_OR_PASTE_HINT: 'or paste YAML / JSON below',
  MODAL_INSOMNIA_TEXTAREA_LABEL: 'Insomnia Collection Content (YAML or JSON)',
  MODAL_INSOMNIA_TEXTAREA_PLACEHOLDER: 'Paste Insomnia collection YAML or JSON here (e.g. type: collection.insomnia.rest/5.0)...',
  MODAL_INSOMNIA_SAMPLE_BTN: 'Insert Sample Insomnia YAML',
  MODAL_INSOMNIA_PREVIEW_TITLE: 'Conversion Preview',
  MODAL_INSOMNIA_STAT_REQUESTS: 'Requests / Steps',
  MODAL_INSOMNIA_STAT_CHAINS: 'Response Chains',
  MODAL_INSOMNIA_STAT_ENVS: 'Base URL Envs',
  MODAL_INSOMNIA_SUBMIT_BTN: 'Convert & Import Flow',
  MODAL_INSOMNIA_SUBMITTING_BTN: 'Converting & Upserting...',
  MODAL_INSOMNIA_ERR_INVALID: 'Failed to parse Insomnia collection. Please check file format.',
  MODAL_INSOMNIA_ERR_EMPTY: 'Please upload an Insomnia YAML/JSON file or paste its content.',

  CARD_NO_DESC: 'No description provided.',
  CARD_OPEN_BUILDER: 'Open Builder',
  CARD_RUN_TEST: 'Run Test',
  TAB_FLOWS_COUNT: (count: number) => `Scenario Flows (${count})`,
  TAB_JOBS: 'Scheduled Jobs',
  OPTIONAL_LABEL: '(Optional)',
  YAML_JSON_V5: 'YAML / JSON v5',
  PASSED_STATUS: (duration: number) => `Passed (${duration}ms)`,
  IMPORT_INSOMNIA_BTN: 'Import Insomnia Collection',
} as const;
