export const API_COLLECTIONS_TEXT = {
  TITLE: 'API Collections & Endpoints',
  SUBTITLE: 'Define mock endpoint contracts and route parameters',
  ADD_COLLECTION_BTN: 'Add API Collection',
  SEARCH_PLACEHOLDER: 'Search endpoint name or path...',
  NO_ENDPOINTS: 'No API collections found',
  ACTION_VIEW_CONFIG: 'View Config',
  ACTION_EDIT: 'Edit Endpoint',
  ACTION_DUPLICATE: 'Duplicate',
  ACTION_DELETE: 'Delete Endpoint',
  ALL_METHODS: 'All Methods',
  ALL_STATUS: 'All Status',
  ACTIVE: 'Active',
  DISABLED: 'Disabled',
  MODAL_ADD_TITLE: 'Add API Collection',
  MODAL_EDIT_TITLE: 'Edit API Collection',
  LABEL_NAME: 'Name / Label *',
  LABEL_METHOD: 'Method *',
  LABEL_PATH: 'Path / Route *',
  LABEL_DESCRIPTION: 'Description',
  LABEL_ACTIVE_STATUS: 'Active Status',
  PLACEHOLDER_NAME: 'e.g. Get User Profile',
  PLACEHOLDER_PATH: '/api/v1/users/:id',
  PLACEHOLDER_DESC: 'Optional notes or documentation...',
  BTN_CANCEL: 'Cancel',
  BTN_CREATE: 'Create Endpoint',
  BTN_SAVE: 'Save Changes',
  DELETE_DIALOG_TITLE: 'Delete API Endpoint?',
  DELETE_DIALOG_DESC: 'Are you sure you want to delete this API endpoint? All associated request and response scenarios will be deleted.',
  DELETE_DIALOG_CONFIRM: 'Delete',
} as const;
