export const ADMIN_ACCOUNTS_TEXT = {
  TITLE: 'User Accounts',
  SUBTITLE: 'Manage system accounts, user permissions, and roles.',
  LOADING_ACCOUNTS: 'Loading user accounts...',
  NO_ACCOUNTS_TITLE: 'No Accounts Registered',
  NO_ACCOUNTS_DESC: 'There are no custom database accounts registered. Add a new account to allow multiple user roles.',
  CREATE_FIRST_BTN: 'Create First Account',
  NO_RESULTS_TITLE: 'No accounts found',
  NO_RESULTS_DESC: 'No accounts match the criteria.',
  RESET_FILTERS: 'Reset Filters',
  ADD_ACCOUNT: 'Add Account',
  EDIT_ACCOUNT: 'Edit User Account',
  ADD_USER_ACCOUNT: 'Add User Account',
  SAVE_ACCOUNT: 'Save Account',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',
  DELETE_CONFIRM_TITLE: 'Delete User Account',
  DELETE_CONFIRM_DESC: 'Are you sure you want to delete this account? This action cannot be undone.',
  SEARCH_PLACEHOLDER: 'Search accounts by name, email, or role...',
  FILTER_ROLE_LABEL: 'Filter Role:',
  ALL_ROLES_OPTION: 'All Roles',
  LABEL_USERNAME: 'Username *',
  LABEL_EMAIL_SSO: 'Email Address (SSO) *',
  LABEL_DISPLAY_NAME: 'Display Name *',
  LABEL_PASSWORD: 'Password',
  LABEL_OPTIONAL: '(Optional)',
  LABEL_REQUIRED: '*',
  LABEL_ACCOUNT_ROLE: 'Account Role *',
  PLACEHOLDER_ADMIN_USERNAME: 'e.g. jdoe',
  PLACEHOLDER_SSO_USERNAME: 'username',
  PLACEHOLDER_DISPLAY_NAME: 'e.g. John Doe',
  PLACEHOLDER_PASSWORD_NEW: '••••••••',
  PLACEHOLDER_PASSWORD_EDIT: 'Leave blank to keep current password',
  SSO_INFO_HINT: 'Non-admin accounts sign in securely via SSO. Passwords are automatically managed.',
  JOINED_PREFIX: 'Joined',
  REQUIRED_FIELDS_ERROR: 'Please fill out all required fields',
  OPERATION_FAILED_ERROR: 'Operation failed',
} as const;

