export const ADMIN_ACCOUNTS_TEXT = {
  TITLE: 'User Accounts',
  SUBTITLE: 'Manage system accounts, user permissions, and roles.',
  LOADING_ACCOUNTS: 'Loading user accounts...',
  NO_ACCOUNTS_TITLE: 'No Accounts Registered',
  NO_ACCOUNTS_DESC: 'There are no custom database accounts registered. Add a new account to allow multiple user roles.',
  CREATE_FIRST_BTN: 'Create First Account',
  NO_RESULTS_TITLE: 'No accounts found',
  NO_RESULTS_DESC: 'No accounts match the criteria.',
  RESET_FILTERS: 'Reset Filters',
  ADD_ACCOUNT: 'Add Account',
  EDIT_ACCOUNT: 'Edit User Account',
  ADD_USER_ACCOUNT: 'Add User Account',
  SAVE_ACCOUNT: 'Save Account',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',
  DELETE_CONFIRM_TITLE: 'Delete User Account',
  DELETE_CONFIRM_DESC: 'Are you sure you want to delete this account? This action cannot be undone.',
  SEARCH_PLACEHOLDER: 'Search accounts by name, email, or role...',
  FILTER_ROLE_LABEL: 'Filter Role:',
  ALL_ROLES_OPTION: 'All Roles',
  LABEL_USERNAME: 'Username *',
  LABEL_EMAIL_SSO: 'Email Address (SSO) *',
  LABEL_DISPLAY_NAME: 'Display Name *',
  LABEL_PASSWORD: 'Password',
  LABEL_OPTIONAL: '(Optional)',
  LABEL_REQUIRED: '*',
  LABEL_ACCOUNT_ROLE: 'Account Role *',
  PLACEHOLDER_ADMIN_USERNAME: 'e.g. jdoe',
  PLACEHOLDER_SSO_USERNAME: 'username',
  PLACEHOLDER_DISPLAY_NAME: 'e.g. John Doe',
  PLACEHOLDER_PASSWORD_NEW: '••••••••',
  PLACEHOLDER_PASSWORD_EDIT: 'Leave blank to keep current password',
  SSO_INFO_HINT: 'Non-admin accounts sign in securely via SSO. Passwords are automatically managed.',
  JOINED_PREFIX: 'Joined',
  REQUIRED_FIELDS_ERROR: 'Please fill out all required fields',
  OPERATION_FAILED_ERROR: 'Operation failed',
  TITLE_REFRESH_LIST: 'Refresh List',
  TITLE_EDIT_USER: 'Edit User',
  TITLE_DELETE_USER: 'Delete User',
  DELETE_CONFIRM_BTN: 'Delete',
  NO_ACCOUNTS_MATCH: (query: string, roleFilter: string) =>
    `No accounts match "${query}" ${roleFilter !== 'All' ? `with role ${roleFilter}` : ''}.`,
  OVERLAY_CREATE_TITLE: (name: string) => `Membuat akun "${name}"`,
  OVERLAY_CREATE_DESC: 'Akun baru sedang dibuat dan akan muncul di daftar admin.',
  ERROR_CREATE_ACCOUNT: 'Failed to create account',
  OVERLAY_UPDATE_TITLE: (name: string) => `Menyimpan akun "${name}"`,
  OVERLAY_UPDATE_DESC: 'Nama, role, atau password akun sedang diperbarui.',
  ERROR_UPDATE_ACCOUNT: 'Failed to update account',
  OVERLAY_DELETE_TITLE: (name?: string) => `Menghapus akun${name ? ` "${name}"` : ''}`,
  OVERLAY_DELETE_DESC: 'Akun sedang dihapus dan tidak akan bisa digunakan untuk masuk.',
  ERROR_DELETE_ACCOUNT: 'Failed to delete account',
  ERROR_LOAD_ACCOUNTS: 'Failed to load accounts',
} as const;


