export const ADMIN_ACCOUNTS_SEMANTIC_ID = {
  CONTAINER: 'admin-accounts-container',
  HEADER: 'admin-accounts-header',
  REFRESH_BTN: 'admin-accounts-refresh-btn',
  ADD_BTN: 'admin-accounts-add-btn',
  SEARCH_INPUT: 'admin-accounts-search-input',
  FILTER_SELECT: 'admin-accounts-filter-select',
  LIST_CONTAINER: 'admin-accounts-list-container',
  CARD_ITEM: 'admin-accounts-card-item',
  CARD_ITEM_PREFIX: (id: string) => `admin-accounts-card-item-${id}`,
  CARD_EDIT_BTN: 'admin-accounts-card-edit-btn',
  CARD_EDIT_BTN_PREFIX: (id: string) => `admin-accounts-card-edit-btn-${id}`,
  CARD_DELETE_BTN: 'admin-accounts-card-delete-btn',
  CARD_DELETE_BTN_PREFIX: (id: string) => `admin-accounts-card-delete-btn-${id}`,
  DIALOG_CONTENT: 'admin-accounts-dialog-content',
  DIALOG_CLOSE_BTN: 'admin-accounts-dialog-close-btn',
  DIALOG_CANCEL_BTN: 'admin-accounts-dialog-cancel-btn',
  INPUT_USERNAME: 'admin-accounts-input-username',
  SELECT_EMAIL_DOMAIN: 'admin-accounts-select-email-domain',
  INPUT_DISPLAY_NAME: 'admin-accounts-input-display-name',
  INPUT_PASSWORD: 'admin-accounts-input-password',
  SELECT_ROLE: 'admin-accounts-select-role',
  DIALOG_SUBMIT_BTN: 'admin-accounts-dialog-submit-btn',
} as const;
