export const SIGN_IN_TEXT = {
  TITLE: 'Mock API Studio',
  SUBTITLE: 'Build predictable APIs before the backend exists.',
  HERO_BADGE: 'OFFLINE-FIRST ENGINE',
  HERO_TITLE_PREFIX: 'Build predictable APIs ',
  HERO_TITLE_SUFFIX: 'before the backend exists.',
  HERO_DESCRIPTION: 'Design endpoints, configure weighted response scenarios, manage multi-environment URLs, and test HTTP rules locally with zero cloud dependencies.',
  HERO_FEATURE_1: '✓ SQLite DB',
  HERO_FEATURE_2: '✓ REST Scenarios',
  HERO_FEATURE_3: '✓ Custom Headers',
  WELCOME_BACK: 'Welcome back',
  WELCOME_SUBTITLE: 'Sign in to manage your local endpoints and environments',
  AUTH_INFO_TITLE: 'Environment-based Auth',
  AUTH_INFO_DESC: 'Login credentials are validated on the proxy API using APP_USERNAME and APP_PASSWORD.',
  USERNAME_LABEL: 'Username',
  USERNAME_PLACEHOLDER: 'Enter username',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter password',
  REMEMBER_ME: 'Remember me',
  SUBMIT_BTN: 'Sign In to Dashboard',
  SUBMITTING_BTN: 'Authenticating...',
  FOOTER_CREDIT: 'Mock API Studio • High-Contrast Editorial Design',
} as const;
