export const API_DETAIL_TEXT = {
  TITLE: 'Endpoint Details',
  SUBTITLE: 'Configure request/response scenarios, mock data, and headers.',
  TAB_SCENARIOS: 'Request & Response Scenarios',
  TAB_OVERVIEW: 'Endpoint Overview',
  NOT_FOUND: 'API Endpoint Not Found',
  BACK_TO_PREFIX: 'Back to',
  STATUS_API_ACTIVE: 'API Active',
  STATUS_API_DISABLED: 'API Disabled',
  SIDEBAR_TITLE: 'Request Scenarios',
  SIDEBAR_ADD_BTN: 'Add',
  SIDEBAR_SEARCH_PLACEHOLDER: 'Search scenario...',
  SIDEBAR_EMPTY: 'No request scenarios matching filter',
  DETAIL_RULE_WEIGHT: 'Weight / Priority',
  DETAIL_PARAM_MATCHING: 'Query Params Matching',
  DETAIL_HEADER_MATCHING: 'Headers Matching',
  DETAIL_BODY_MATCHING: 'Body Payload Matching',
  RESPONSES_TITLE: 'Attached Response Scenarios',
  RESPONSES_ADD_BTN: 'Add Response Scenario',
  OVERVIEW_PROJECT_ID: 'Project ID',
  OVERVIEW_ENDPOINT_ID: 'Endpoint ID',
  OVERVIEW_METHOD: 'HTTP Method',
  OVERVIEW_ROUTE: 'Route Path',
  OVERVIEW_CREATED: 'Created Date',
  MODAL_REQ_ADD_TITLE: 'Add Request Scenario',
  MODAL_REQ_EDIT_TITLE: 'Edit Request Scenario',
  MODAL_RESP_ADD_TITLE: 'Add Response Scenario',
  MODAL_RESP_EDIT_TITLE: 'Edit Response Scenario',
  LABEL_SCENARIO_NAME: 'Scenario Name *',
  LABEL_PRIORITY: 'Priority / Weight',
  LABEL_STATUS_CODE: 'HTTP Status Code *',
  LABEL_RESPONSE_BODY: 'JSON Response Payload *',
  LABEL_DELAY: 'Simulated Delay (ms)',
  LABEL_ACTIVE_STATUS: 'Active Status',
  BTN_CANCEL: 'Cancel',
  BTN_CREATE: 'Create Scenario',
  BTN_SAVE: 'Save Changes',
  DELETE_REQ_DIALOG_TITLE: 'Delete Request Scenario?',
  DELETE_REQ_DIALOG_DESC: 'Are you sure you want to delete this scenario and all attached response payloads?',
  DELETE_RESP_DIALOG_TITLE: 'Delete Response Scenario?',
  DELETE_RESP_DIALOG_DESC: 'Are you sure you want to delete this mock response payload?',
  PLACEHOLDER_REQ_NAME: 'e.g. Valid VIP Customer Request',
  PLACEHOLDER_RESP_NAME: 'e.g. 200 OK Response',
  PLACEHOLDER_KEY: 'Key',
  PLACEHOLDER_VALUE: 'Value',
  PLACEHOLDER_FILE_PATTERN: 'File name pattern (e.g. avatar.png)',
  PLACEHOLDER_STATUS_CODE: '200',
  PLACEHOLDER_DELAY: '0',
  PLACEHOLDER_WEIGHT: '100',
  TAB_HEADERS: 'Headers',
  TAB_QUERY_PARAMS: 'Query Params',
  TAB_PATH_PARAMS: 'Path Params',
  TAB_BODY_PAYLOAD: 'Body Payload',
  OVERVIEW_TAB_DESC: 'System attributes and configuration parameters for this API endpoint.',
  OVERVIEW_STATUS: 'Status',
  BACK_TO_PROJECT_BTN: 'Back to Project',
  NO_SCENARIO_SELECTED_TITLE: 'No scenario selected',
  NO_SCENARIO_SELECTED_DESC: 'Select or add a request scenario from the left panel to configure headers, parameters, matching rules, and mock responses.',
  ACTION_EDIT_RULE: 'Edit Rule',
  ACTION_DUPLICATE_RULE: 'Duplicate Rule',
  ACTION_DELETE_RULE: 'Delete Rule',
  MATCHING_FULL_BODY: 'Full Body Payload Matching',
  MATCHING_FORM_DATA: 'Body Fields & Files Matching',
  MATCHING_URL_ENCODED: 'URL Encoded Fields Matching',
  BODY_NONE_NOTICE: 'Skenario ini tidak mengevaluasi request body (Body Type: None).',
  BODY_PATH_RULES_COUNT: (count: number) => `Body Path Rules (${count})`,
  STRICT_STRUCTURE_LABEL: 'Strict Structure:',
  NO_RESPONSE_SCENARIOS: 'No response scenarios configured. Add a response payload (e.g. 200 OK, 400 Bad Request, 500 Error).',
  ACTION_EDIT_RESPONSE: 'Edit Response',
  ACTION_DUPLICATE_RESPONSE: 'Duplicate Response',
  ACTION_DELETE_RESPONSE: 'Delete Response',
  STRATEGY_MATCH_ANY: 'Match ANY (OR)',
  STRATEGY_MATCH_ALL: 'Match ALL (AND)',
} as const;

