export const API_DETAIL_SEMANTIC_ID = {
  CONTAINER: 'api-detail-container',
  HEADER: 'api-detail-header',
  BACK_BTN: 'api-detail-back-btn',
  MAIN_TABS: 'api-detail-main-tabs',
  MAIN_TAB: (tab: string) => `api-detail-tab-${tab}`,
  SCENARIO_SIDEBAR: 'api-detail-scenario-sidebar',
  SCENARIO_SIDEBAR_SEARCH: 'api-detail-scenario-sidebar-search',
  SCENARIO_SIDEBAR_ADD_BTN: 'api-detail-scenario-sidebar-add-btn',
  SCENARIO_ITEM: (id: string) => `api-detail-scenario-item-${id}`,
  SCENARIO_DETAIL: 'api-detail-scenario-detail',
  SCENARIO_ACTION_EDIT: 'api-detail-scenario-action-edit',
  SCENARIO_ACTION_DUPLICATE: 'api-detail-scenario-action-duplicate',
  SCENARIO_ACTION_DELETE: 'api-detail-scenario-action-delete',
  RESPONSES_SECTION: 'api-detail-responses-section',
  RESPONSES_ADD_BTN: 'api-detail-responses-add-btn',
  RESP_CARD: (id: string) => `api-detail-resp-card-${id}`,
  RESP_ACTION_EDIT: (id: string) => `api-detail-resp-action-edit-${id}`,
  RESP_ACTION_DUPLICATE: (id: string) => `api-detail-resp-action-duplicate-${id}`,
  RESP_ACTION_DELETE: (id: string) => `api-detail-resp-action-delete-${id}`,
  ENV_TAB_CONTENT: 'api-detail-env-tab-content',
  OVERVIEW_TAB_CONTENT: 'api-detail-overview-tab-content',
  REQ_MODAL: 'api-detail-req-modal',
  RESP_MODAL: 'api-detail-resp-modal',
  RESP_MODAL_CLOSE_BTN: 'api-detail-resp-modal-close-btn',
  RESP_MODAL_BTN_CANCEL: 'api-detail-resp-modal-btn-cancel',
  RESP_MODAL_BEAUTIFY_BTN: 'api-detail-resp-modal-beautify-btn',
  REQ_FORM_INPUT_NAME: 'api-detail-req-form-input-name',
  REQ_FORM_PRIORITY: 'api-detail-req-form-priority',
  REQ_FORM_QUERY_PARAMS: 'api-detail-req-form-query-params',
  REQ_FORM_HEADERS: 'api-detail-req-form-headers',
  REQ_FORM_BODY_TYPE: 'api-detail-req-form-body-type',
  REQ_FORM_BODY: 'api-detail-req-form-body',
  REQ_FORM_STATUS: 'api-detail-req-form-status',
  REQ_FORM_FOOTER: 'api-detail-req-form-footer',
  REQ_FORM_BTN_SUBMIT: 'api-detail-req-form-btn-submit',
  RESP_FORM_INPUT_NAME: 'api-detail-resp-form-input-name',
  RESP_FORM_STATUS_CODE: 'api-detail-resp-form-status-code',
  RESP_FORM_PRIORITY: 'api-detail-resp-form-priority',
  RESP_FORM_WEIGHT: 'api-detail-resp-form-weight',
  RESP_FORM_TYPE_JSON: 'api-detail-resp-form-type-json',
  RESP_FORM_TYPE_FILE: 'api-detail-resp-form-type-file',
  RESP_FORM_FILE_UPLOAD: 'api-detail-resp-form-file-upload',
  RESP_FORM_BODY: 'api-detail-resp-form-body',
  RESP_FORM_STATUS: 'api-detail-resp-form-status',
  RESP_FORM_FOOTER: 'api-detail-resp-form-footer',
  RESP_FORM_BTN_SUBMIT: 'api-detail-resp-form-btn-submit',
} as const;

