export const SCENARIO_FLOW_DETAIL_TEXT = {
  BACK_TO_FLOWS: 'Back to Flows',
  BACK_TO_SCENARIO_FLOWS: 'Back to Scenario Flows',
  RUN_TEST_BTN: 'Run Real Testing',
  RUN_TEST: 'Run Test',
  RUNNING_BTN: 'Executing Steps...',
  EXPORT_BTN: 'Export JSON',
  ADD_STEP_BTN: 'Add Step',
  ADD_FIRST_STEP: 'Add First Step',
  HISTORY_BTN: 'Run History',
  STEPS_HEADER: 'Chained Steps Sequence',
  RUNNER_HEADER: 'Live Test Runner & Inspector',
  TARGET_ENV_LABEL: 'Target Environment',
  TARGET_MODE_LABEL: 'Target Mode',
  MOCK_MODE: 'Internal Mock',
  LIVE_MODE: 'Live Backend',
  NO_STEPS_TITLE: 'No Steps in this Flow',
  NO_STEPS_DESC: 'Add your first API step to begin building the chained scenario.',
  EXTRACTORS_LABEL: 'Variable Extractors',
  ASSERTIONS_LABEL: 'Assertions',
  EXECUTION_SUMMARY: 'Execution Summary',
  LOADING_TITLE: 'Loading scenario flow details...',
  NOT_FOUND_TITLE: 'Flow Not Found',
  NOT_FOUND_DESC: 'The requested scenario flow does not exist or was deleted.',
  ACTIVE_STATUS: 'Active',
  DRAFT_STATUS: 'Draft',
  CROSS_PROJECT: 'Cross-Project Flow',
  DIAGRAM_FLOW: 'Diagram Flow',
  CLASSIC_LIST: 'Classic List',
  EDIT_FLOW_TOOLTIP: 'Edit Flow Title & Description',
  ADD_DESCRIPTION_PLACEHOLDER: '+ Add flow description...',
  DRAWER_TITLE: 'Live Runner & Step Inspector',
  DRAWER_SUBTITLE: 'Inspect sent payload, headers, response, and assertions',
  CLOSE_INSPECTOR: 'Close Inspector',
  RUNNING_LABEL: (seconds: string) => `RUNNING (${seconds}s)`,
  RUN_ITERATIONS_TITLE: 'Run Iterations',
  LOOP_TEST_BADGE: 'Loop Test',
  SINGLE_RUN: 'Run 1x (Single Run)',
  RUN_3X: 'Run 3x (Loop 3 times)',
  RUN_5X: 'Run 5x (Loop 5 times)',
  RUN_10X: 'Run 10x (Loop 10 times)',
  CUSTOM_N_LABEL: 'Run Custom N Times:',
  RUN_NX_BTN: (n: number) => `Run ${n}x`,
  HISTORY_MODAL_TITLE: 'Execution Run History',
  HISTORY_MODAL_SUBTITLE: 'Inspect past test results, durations, assertions, and download logs',
  HISTORY_STATUS_PASSED: 'Passed',
  HISTORY_STATUS_FAILED: 'Failed',
  HISTORY_EXPORT_MD_TITLE: 'Download test execution log as Markdown (.md)',
  HISTORY_EXPORT_CSV_TITLE: 'Download test execution log as CSV (.csv)',
  NO_EXECUTIONS: 'No executions recorded yet.',
  EXPORT_MD: 'Export MD',
  EXPORT_CSV: 'Export CSV',
  EDIT_FLOW_TITLE: 'Edit Scenario Flow',
  EDIT_FLOW_SUBTITLE: 'Update flow metadata, default execution environment, and shared variables.',
  EDIT_NAME_LABEL: 'Flow Name',
  EDIT_NAME_PLACEHOLDER: 'e.g. User Registration & Checkout Flow',
  EDIT_DESC_LABEL: 'Description',
  EDIT_DESC_PLACEHOLDER: 'Optional description of this test journey...',
  EDIT_ENV_LABEL: 'Default Target Environment',
  EDIT_ENV_NONE: '-- None (Prompt on Run) --',
  EDIT_STOP_ON_FAILURE_LABEL: 'Stop on Failure',
  EDIT_STOP_ON_FAILURE_DESC: 'Halt remaining steps if a step fails',
  EDIT_VARS_LABEL: 'Initial Variables (JSON)',
  EDIT_VARS_ERROR: 'Invalid JSON format for variables',
  SAVE_CHANGES: 'Save Changes',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',

  // FlowExecutionPanel
  READY_FOR_TESTING_TITLE: 'Ready for Real Testing',
  READY_FOR_TESTING_DESC: 'Click "Run Real Testing" to execute all steps sequentially on the server.',
  EXECUTING_FLOW_TITLE: 'Executing Scenario Flow...',
  EXECUTING_FLOW_DESC: 'Sending chained HTTP requests sequentially & validating assertions',
  ALL_STEPS_PASSED: 'All Steps Passed',
  EXECUTION_FAILED_PREFIX: 'Execution Failed',
  EXECUTION_TIMELINE_LABEL: 'Execution Timeline',
  STEP_ORDER_LABEL: (order: number) => `Step ${order}`,
  TABLE_HEADER_STEP: '#',
  TABLE_HEADER_NAME: 'Step Name',
  TABLE_HEADER_METHOD: 'Method',
  TABLE_HEADER_STATUS: 'Status',
  TABLE_HEADER_DURATION: 'Duration',
  TABLE_PAGINATION_SHOWING: (from: number, to: number, total: number) => `${from}-${to} of ${total}`,
  TABLE_PAGE_LABEL: (page: number, totalPages: number) => `${page} / ${totalPages}`,
  TABLE_PREV: 'Previous',
  TABLE_NEXT: 'Next',
  NO_STEPS_RECORDED: 'No step executions recorded',
  STEPS_PAGINATION_SHOWING: (from: number, to: number, total: number) => `${from}-${to} of ${total} steps`,
  STEPS_PAGE_LABEL: (page: number, totalPages: number) => `${page} / ${totalPages}`,
  STEPS_PREV: 'Previous',
  STEPS_NEXT: 'Next',

  // Step Card
  STEP_CARD_RUNNING: 'RUNNING',
  STEP_CARD_RUN_BTN: 'Run Step',
  STEP_CARD_RUN_TOOLTIP: 'Run this step only and inspect isolated execution result',
  STEP_CARD_ENABLED: 'Enabled',
  STEP_CARD_DISABLED: 'Disabled',
  STEP_CARD_LOCAL_ONLY: 'LOCAL ONLY',
  STEP_CARD_SCENARIO_LABEL: 'Scenario:',
  STEP_CARD_MOVE_UP: 'Move Up',
  STEP_CARD_MOVE_DOWN: 'Move Down',
  STEP_CARD_EDIT_TOOLTIP: 'Edit Step',
  STEP_CARD_DELETE_TOOLTIP: 'Delete Step',
  STEP_CARD_DOUBLE_CLICK_TOOLTIP: 'Double-click to open step inspector',
  STEP_CARD_DELAY_LABEL: (ms: number) => `${ms}ms delay`,
  STEP_CARD_CONTINUE_ON_ERROR: 'continue on error',

  // Canvas
  CANVAS_EMPTY_TITLE: 'Flow Diagram is Empty',
  CANVAS_EMPTY_DESC: 'Start building your chained API flow by adding your first step.',
  CANVAS_EMPTY_ADD_FIRST_STEP: 'Add First Step',
  CANVAS_AUTO_ARRANGE: 'Auto-Arrange',
  CANVAS_AUTO_ARRANGE_TOOLTIP: 'Auto-Arrange Layout (Align Left-to-Right)',
  CANVAS_ADD_STEP: 'Add Step',
  CANVAS_ADD_STEP_TOOLTIP: 'Add New Step',
  CANVAS_HIDE_INSPECTOR: 'Hide Inspector',
  CANVAS_LIVE_INSPECTOR: 'Live Inspector',
  CANVAS_ZOOM_IN_TOOLTIP: 'Zoom In',
  CANVAS_ZOOM_OUT_TOOLTIP: 'Zoom Out',
  CANVAS_RESET_ZOOM_TOOLTIP: 'Reset View (100%)',
  CANVAS_HINT_PAN: 'Drag canvas to pan',
  CANVAS_HINT_ZOOM: 'Wheel to zoom',
  CANVAS_HINT_REPOSITION: 'Drag cards to reposition',
  CANVAS_STEP_INDEX_LABEL: (index: number, total: number) => `STEP ${index} OF ${total}`,
  CANVAS_PORT_INPUT_TOOLTIP: 'Input Connector',
  CANVAS_PORT_OUTPUT_TOOLTIP: 'Output Connector',

  // Step Inspector
  INSPECTOR_DISPATCHING_TITLE: 'Dispatching API Request...',
  INSPECTOR_DISPATCHING_DESC: 'Executing HTTP request, calculating duration, and running assertions...',
  INSPECTOR_NO_STEP_SELECTED: 'No Step Selected',
  INSPECTOR_NO_STEP_DESC: 'View sent headers, payload, response body, and assertions',
  INSPECTOR_TAB_RESPONSE: 'Response Body',
  INSPECTOR_TAB_REQUEST: 'Request Sent',
  INSPECTOR_TAB_ASSERTIONS: (count: number) => `Assertions (${count})`,
  INSPECTOR_TAB_VARIABLES: 'Extracted Variables',
  INSPECTOR_FULL_URL_LABEL: 'Full Request URL',
  INSPECTOR_REQUEST_HEADERS_LABEL: 'Request Headers',
  INSPECTOR_REQUEST_BODY_LABEL: 'Request Body',
  INSPECTOR_NO_ASSERTIONS_EVALUATED: 'No explicit assertions evaluated (verified HTTP 2xx/3xx).',
  INSPECTOR_ACTUAL_LABEL: 'Actual:',
  INSPECTOR_NO_VARIABLES_EXTRACTED: 'No variables were extracted by this step.',
  INSPECTOR_COL_VARIABLE: 'Variable',
  INSPECTOR_COL_VALUE_SAVED: 'Value Saved to Context',

  // Add Step Modal
  MODAL_STEP_TITLE_EDIT: 'Edit Step',
  MODAL_STEP_TITLE_CREATE: 'Add Step to Flow',
  MODAL_STEP_SUBTITLE: 'Configure API endpoint, dynamic parameters, extractors, and assertions',
  TAB_BASIC_API: 'Basic & API',
  TAB_OVERRIDES_BODY: 'Overrides & Body',
  TAB_EXTRACTORS: (count: number) => `Extractors (${count})`,
  TAB_ASSERTIONS: (count: number) => `Assertions (${count})`,
  FIELD_STEP_NAME: 'Step Name',
  FIELD_STEP_NAME_PLACEHOLDER: 'e.g. Authenticate User or Fetch Profile',
  FIELD_SELECT_API: 'Select API',
  FIELD_PROJECT_LABEL: 'Project:',
  FIELD_ALL_PROJECTS: (count: number) => `All Projects (${count})`,
  FIELD_REQUEST_SCENARIO_PRESET: 'Request Scenario Preset',
  FIELD_LOADING_SCENARIOS: 'Loading scenarios...',
  FIELD_CUSTOM_SCENARIO_OPTION: '-- Custom / Step specific parameters --',
  FIELD_METHOD: 'Method',
  FIELD_PATH: 'Endpoint Path',
  FIELD_PATH_HINT: '(supports {{var}})',
  FIELD_PATH_PLACEHOLDER: '/api/v1/users/{{userId}}',
  FIELD_DELAY_MS: 'Step Delay (ms)',
  FIELD_DELAY_MS_PLACEHOLDER: '0',
  FIELD_CONTINUE_ON_ERROR: 'Continue on Error',
  FIELD_CONTINUE_ON_ERROR_DESC: "Don't halt flow on error",
  TARGET_ENV_BASE_URL_LABEL: 'Target Environment Base URL',
  TARGET_ENV_DESC_LOCAL: 'Khusus step ini ke local APP_URL',
  TARGET_ENV_DESC_DEFAULT: 'Mengikuti switcher env di header flow',
  TARGET_ENV_BTN_DEFAULT: 'Default (Ikuti Header)',
  TARGET_ENV_BTN_LOCAL: 'Local (Khusus Step Ini)',
  TARGET_ENV_SERVICE_LABEL: 'Pilih Service Base URL / Target Environment',
  TARGET_ENV_SERVICE_HINT: 'dari daftar Environments proyek',
  TARGET_ENV_SERVICE_AUTO: '-- Auto (Gunakan Base URL Terkait API / Flow Default) --',
  TARGET_ENV_SERVICE_REGISTERED_FOR: (label: string) => `Base URLs terdaftar untuk ${label}:`,
  TARGET_ENV_SERVICE_NO_STAGE: 'Belum ada URL stage yang dikonfigurasi',
  TOKEN_HELPER_TITLE: 'Use dynamic variables, envs, or datasets:',
  TOKEN_HELPER_DESC: (focused: string) => `Token will be inserted into active field (focused: ${focused})`,
  FIELD_HEADERS_OVERRIDE: 'Headers Override (JSON)',
  FIELD_HEADERS_OVERRIDE_HINT: 'e.g. { "Authorization": "Bearer {{token}}" }',
  FIELD_QUERY_PARAMS_OVERRIDE: 'Query Parameters Override (JSON)',
  FIELD_BODY_CONTENT_TYPE: 'Request Body Content-Type',
  BODY_TYPE_JSON: 'JSON (application/json)',
  BODY_TYPE_FORM_DATA: 'Form Data (multipart/form-data)',
  BODY_TYPE_URL_ENCODED: 'URL Encoded (application/x-www-form-urlencoded)',
  BODY_TYPE_NONE: 'None (No Request Body)',
  BODY_NONE_DESC: 'No request body will be sent for this step.',
  BODY_MODE_FORM_FIELDS: (count: number) => `Form Fields (${count})`,
  BODY_MODE_RAW_JSON: 'Raw JSON',
  BTN_ADD_FIELD: 'Add Field',
  BODY_RAW_HINT: 'Supports {{var}}, {{$uuid}}',
  NO_FORM_FIELDS_DESC: (type: string) => `No form fields configured yet for this ${type} payload.`,
  BTN_ADD_FIRST_FIELD: 'Add First Field',
  FIELD_KEY_PLACEHOLDER: 'Field key / name',
  FIELD_VALUE_PLACEHOLDER: 'Field value (supports {{var}})',
  FIELD_VALUE_FILE_PLACEHOLDER: 'Filename (e.g. avatar.png, {{fileName}})',
  FIELD_FILE_LABEL: 'File',
  EXTRACTORS_DESC: 'Extract data from this response to reuse in subsequent steps as {{variable}}.',
  BTN_ADD_EXTRACTOR: 'Add Extractor',
  EXTRACTORS_EMPTY: "No extractors configured. Click 'Add Extractor' to pass tokens, IDs, or values to next steps.",
  EXTRACTOR_VAR_PLACEHOLDER: 'Variable name (e.g. authToken)',
  EXTRACTOR_PATH_PLACEHOLDER: 'Path (e.g. data.token or items[0].id)',
  ASSERTIONS_DESC: 'Verify response values to ensure the API behaves as expected.',
  BTN_ADD_ASSERTION: 'Add Assertion',
  ASSERTIONS_EMPTY: 'No assertions configured. Defaults to HTTP 2xx/3xx check.',
  BTN_EDIT_REQ_RES_SCENARIO: 'Edit Req & Res Scenario (API Detail)',
  BTN_EDIT_REQ_RES_SCENARIO_TOOLTIP: 'Buka halaman API Detail di tab baru untuk mengedit Request & Response Scenarios lokal',
  BTN_CANCEL: 'Cancel',
  BTN_UPDATE_STEP: 'Update Step',
  BTN_ADD_STEP: 'Add Step',
  ERR_STEP_NAME_REQUIRED: 'Step name is required',
  ERR_INVALID_JSON_STEP: 'Invalid JSON format in Headers, Query Params, or Body override.',
  BTN_SAVE_STEP: 'Save Step',
  BTN_SAVING_STEP: 'Saving Step...',

  // Flow Jobs Tab & Modal
  JOBS_TITLE: 'Scheduled Automation Jobs',
  JOBS_SUBTITLE: 'Automate scenario flow executions continuously, on intervals, or iterated over Data Sheets.',
  JOBS_FILTER_ALL: 'All Statuses',
  JOBS_FILTER_ACTIVE: 'Active Only',
  JOBS_FILTER_PAUSED: 'Paused',
  JOBS_FILTER_COMPLETED: 'Completed',
  JOBS_FILTER_FAILED: 'Failed',
  JOBS_CREATE_BTN: 'Create Job',
  JOBS_LOADING: 'Loading scheduled jobs...',
  JOBS_EMPTY_TITLE: 'No Scheduled Jobs Yet',
  JOBS_EMPTY_DESC: 'Create a job to run this flow periodically (e.g. every 5 minutes, daily) or iterate through rows in a Data Sheet automatically.',
  JOBS_CREATE_FIRST_BTN: 'Create First Job',
  JOBS_PAUSE_TOOLTIP: 'Pause Job',
  JOBS_RESUME_TOOLTIP: 'Resume / Activate Job',
  JOBS_EDIT_TOOLTIP: 'Edit Job',
  JOBS_DELETE_TOOLTIP: 'Delete Job',
  JOBS_NEXT_RUN_LABEL: 'Next Run:',
  JOBS_NO_UPCOMING: 'No upcoming run scheduled',
  JOBS_EXECUTING_SOON: 'Executing soon...',
  JOBS_PAUSED_INACTIVE: 'Paused / Inactive',
  JOBS_ITERATION_HEADER: 'Iteration',
  JOBS_SUCCESS_HEADER: 'Success',
  JOBS_FAILED_HEADER: 'Failed',
  JOBS_RUN_NOW: 'Run Now',
  JOBS_RUNNING: 'Running...',
  JOBS_NEVER_EXECUTED: 'Never executed',
  JOBS_LAST_RUN: (time: string) => `Last run: ${time}`,
  JOBS_RUN_EVERY_SEC: (s: number) => `Every ${s} sec(s)`,
  JOBS_RUN_EVERY_MIN: (m: number) => `Every ${Math.round(m)} min(s)`,
  JOBS_RUN_EVERY_HOUR: (h: number) => `Every ${Math.round(h)} hour(s)`,
  JOBS_RUN_ONCE_AT: (time: string) => `Once at ${time}`,
  JOBS_ONE_TIME_RUN: 'One-time run',
  JOBS_IN_SECONDS: (s: number, time: string) => `In ${s}s (${time})`,
  JOBS_IN_MINUTES: (m: number, time: string) => `In ${m}m (${time})`,
  JOBS_ON_DATE: (date: string, time: string) => `On ${date} at ${time}`,
  JOB_MODAL_CREATE_TITLE: 'Create Job Schedule',
  JOB_MODAL_EDIT_TITLE: 'Edit Scheduled Job',
  JOB_MODAL_SUBTITLE: 'Configure automated cron schedules, Data Sheet iteration, and stop conditions.',
  JOB_MODAL_TARGET_FLOW: 'Target Scenario Flow',
  JOB_MODAL_NAME: 'Job Name',
  JOB_MODAL_NAME_PLACEHOLDER: 'e.g. Daily Payment Reconciliation, Bulk User Seed',
  JOB_MODAL_DESC: 'Description',
  JOB_MODAL_DESC_OPTIONAL: '(Optional)',
  JOB_MODAL_DESC_PLACEHOLDER: 'Purpose of this automated scheduled flow...',
  JOB_MODAL_TARGET_ENV: 'Target Environment',
  JOB_MODAL_DEFAULT_ENV: 'Default Flow Environment',
  JOB_MODAL_EXEC_MODE: 'Execution Mode',
  JOB_MODAL_LIVE_REQ: 'Live Request',
  JOB_MODAL_MOCK_PROXY: 'Mock Proxy',
  JOB_MODAL_SCHEDULE_TRIGGER: 'Schedule Trigger',
  JOB_MODAL_CRON_EXPR: 'Cron Expression',
  JOB_MODAL_QUICK_PRESETS: 'Quick Presets:',
  JOB_MODAL_RUN_EVERY: 'Run Every',
  JOB_MODAL_SECONDS: 'Seconds',
  JOB_MODAL_MINUTES: 'Minutes',
  JOB_MODAL_HOURS: 'Hours',
  JOB_MODAL_RUN_AT: 'Run At (Date & Time)',
  JOB_MODAL_DATA_SOURCE: 'Data Source & Variables',
  JOB_MODAL_DATA_SOURCE_DEFAULT: 'Default',
  JOB_MODAL_DATA_SOURCE_DATASHEET: 'Data Sheet',
  JOB_MODAL_DATA_SOURCE_JSON: 'Custom JSON',
  JOB_MODAL_SELECT_DATASHEET: 'Select Data Sheet',
  JOB_MODAL_CHOOSE_DATASHEET: '-- Choose Data Sheet --',
  JOB_MODAL_ITERATION_MODE: 'Iteration Mode',
  JOB_MODAL_ITERATION_PER_TICK: '1 Row per Scheduled Trigger (Sequential)',
  JOB_MODAL_ITERATION_BATCH_ALL: 'Run All Rows per Trigger (Batch)',
  JOB_MODAL_DATASHEET_HINT: 'Row column values (e.g. {{userId}}, {{amount}}) will be automatically injected into flow steps.',
  JOB_MODAL_STATIC_JSON: 'Static JSON Variables',
  JOB_MODAL_JSON_FORMAT: 'JSON format',
  JOB_MODAL_STOP_CONDITION: 'Stop / Termination Condition',
  JOB_MODAL_STOP_FOREVER: 'Continuous (Run forever until manual pause)',
  JOB_MODAL_STOP_MAX_ITER: 'Limit by Total Iteration Count',
  JOB_MODAL_STOP_UNTIL_DATE: 'Stop at Specific Date & Time',
  JOB_MODAL_STOP_DATASHEET_END: 'Stop when Data Sheet Rows End',
  JOB_MODAL_MAX_ITERATIONS: 'Max Iterations',
  JOB_MODAL_MAX_ITERATIONS_PLACEHOLDER: 'e.g. 50',
  JOB_MODAL_END_DATE: 'End Date & Time',
  JOB_MODAL_ERR_SELECT_FLOW: 'Please select a scenario flow',
  JOB_MODAL_ERR_NAME_REQ: 'Please enter a job name',
  JOB_MODAL_SAVE_CHANGES: 'Save Changes',
  JOB_MODAL_CREATE_JOB_BTN: 'Create Job Schedule',
} as const;

