export const SCENARIO_FLOW_DETAIL_SEMANTIC_ID = {
  CONTAINER: 'scenario-flow-detail-container',
  HEADER: 'scenario-flow-detail-header',
  BACK_BTN: 'scenario-flow-detail-back-btn',
  TITLE: 'scenario-flow-detail-title',
  EDIT_FLOW_BTN: 'scenario-flow-detail-edit-flow-btn',
  STATUS_BADGE: 'scenario-flow-detail-status-badge',
  PROJECT_BADGE: 'scenario-flow-detail-project-badge',
  VIEW_MODE_CANVAS: 'scenario-flow-detail-view-mode-canvas',
  VIEW_MODE_LIST: 'scenario-flow-detail-view-mode-list',
  ENV_SELECT: 'scenario-flow-detail-env-select',
  HISTORY_BTN: 'scenario-flow-detail-history-btn',
  EXPORT_BTN: 'scenario-flow-detail-export-btn',
  ADD_STEP_BTN: 'scenario-flow-detail-add-step-btn',
  RUN_BTN: 'scenario-flow-detail-run-btn',
  RUN_BTN_TRIGGER: 'scenario-flow-run-btn-trigger',
  RUN_PRESET_PREFIX: (n: number) => `scenario-flow-run-preset-${n}x`,
  RUN_CUSTOM_INPUT: 'scenario-flow-run-custom-input',
  RUN_CUSTOM_SUBMIT: 'scenario-flow-run-custom-submit',
  CANVAS_CONTAINER: 'scenario-flow-detail-canvas-container',
  CANVAS_TOOLBAR_ADD: 'scenario-flow-detail-canvas-toolbar-add',
  CANVAS_TOOLBAR_ARRANGE: 'scenario-flow-detail-canvas-toolbar-arrange',
  CANVAS_TOOLBAR_INSPECTOR: 'scenario-flow-detail-canvas-toolbar-inspector',
  STEPS_LIST: 'scenario-flow-detail-steps-list',
  STEP_CARD_PREFIX: (id: string | number) => `scenario-flow-step-card-${id}`,
  STEP_CARD_MOVE_UP_PREFIX: (id: string | number) => `scenario-flow-step-move-up-${id}`,
  STEP_CARD_MOVE_DOWN_PREFIX: (id: string | number) => `scenario-flow-step-move-down-${id}`,
  STEP_CARD_EDIT_PREFIX: (id: string | number) => `scenario-flow-step-edit-${id}`,
  STEP_CARD_DELETE_PREFIX: (id: string | number) => `scenario-flow-step-delete-${id}`,
  STEP_CARD_RUN_PREFIX: (id: string | number) => `scenario-flow-step-run-${id}`,
  STEP_CARD_TOGGLE_PREFIX: (id: string | number) => `scenario-flow-step-toggle-${id}`,
  CANVAS_NODE_PREFIX: (id: string | number) => `scenario-flow-canvas-node-${id}`,
  CANVAS_NODE_RUN_PREFIX: (id: string | number) => `scenario-flow-canvas-node-run-${id}`,
  CANVAS_ZOOM_IN_BTN: 'scenario-flow-canvas-zoom-in-btn',
  CANVAS_ZOOM_OUT_BTN: 'scenario-flow-canvas-zoom-out-btn',
  CANVAS_RESET_ZOOM_BTN: 'scenario-flow-canvas-reset-zoom-btn',
  DRAWER: 'scenario-flow-detail-drawer',
  DRAWER_CLOSE_BTN: 'scenario-flow-detail-drawer-close-btn',
  EXECUTION_PANEL: 'scenario-flow-detail-execution-panel',
  EXECUTION_TIMELINE: 'scenario-flow-execution-timeline',
  EXECUTION_STEP_PREFIX: (idx: number) => `scenario-flow-execution-step-${idx}`,
  EXECUTION_EXPORT_MD: 'scenario-flow-execution-export-md',
  EXECUTION_EXPORT_CSV: 'scenario-flow-execution-export-csv',
  STEP_INSPECTOR: 'scenario-flow-detail-step-inspector',
  INSPECTOR_TAB_PREFIX: (tab: string) => `scenario-flow-inspector-tab-${tab}`,
  MODAL_ADD_STEP: 'scenario-flow-detail-modal-add-step',
  MODAL_ADD_STEP_TAB_BASIC: 'scenario-flow-add-step-tab-basic',
  MODAL_ADD_STEP_TAB_PAYLOAD: 'scenario-flow-add-step-tab-payload',
  MODAL_ADD_STEP_TAB_EXTRACTORS: 'scenario-flow-add-step-tab-extractors',
  MODAL_ADD_STEP_TAB_ASSERTIONS: 'scenario-flow-add-step-tab-assertions',
  MODAL_ADD_STEP_INPUT_NAME: 'scenario-flow-add-step-input-name',
  MODAL_ADD_STEP_SELECT_API: 'scenario-flow-add-step-select-api',
  MODAL_ADD_STEP_SELECT_PROJECT: 'scenario-flow-add-step-select-project',
  MODAL_ADD_STEP_SELECT_SCENARIO: 'scenario-flow-add-step-select-scenario',
  MODAL_ADD_STEP_INPUT_METHOD: 'scenario-flow-add-step-input-method',
  MODAL_ADD_STEP_INPUT_PATH: 'scenario-flow-add-step-input-path',
  MODAL_ADD_STEP_INPUT_DELAY: 'scenario-flow-add-step-input-delay',
  MODAL_ADD_STEP_SWITCH_CONTINUE: 'scenario-flow-add-step-switch-continue',
  MODAL_ADD_STEP_BTN_ADD_EXTRACTOR: 'scenario-flow-add-step-btn-add-extractor',
  MODAL_ADD_STEP_BTN_ADD_ASSERTION: 'scenario-flow-add-step-btn-add-assertion',
  MODAL_ADD_STEP_BTN_ADD_FIELD: 'scenario-flow-add-step-btn-add-field',
  MODAL_ADD_STEP_BTN_EDIT_API_DETAIL: 'scenario-flow-add-step-btn-edit-api-detail',
  MODAL_ADD_STEP_BTN_SUBMIT: 'scenario-flow-add-step-btn-submit',
  MODAL_ADD_STEP_BTN_CANCEL: 'scenario-flow-add-step-btn-cancel',
  MODAL_ADD_STEP_BTN_CLOSE: 'scenario-flow-add-step-btn-close',
  MODAL_EDIT_FLOW: 'scenario-flow-detail-modal-edit-flow',
  MODAL_EDIT_INPUT_NAME: 'scenario-flow-edit-input-name',
  MODAL_EDIT_INPUT_DESC: 'scenario-flow-edit-input-desc',
  MODAL_EDIT_SELECT_ENV: 'scenario-flow-edit-select-env',
  MODAL_EDIT_SWITCH_STOP: 'scenario-flow-edit-switch-stop',
  MODAL_EDIT_TEXTAREA_VARS: 'scenario-flow-edit-textarea-vars',
  MODAL_EDIT_BTN_SUBMIT: 'scenario-flow-edit-btn-submit',
  MODAL_EDIT_BTN_CANCEL: 'scenario-flow-edit-btn-cancel',
  MODAL_HISTORY: 'scenario-flow-detail-modal-history',
  MODAL_HISTORY_ITEM_PREFIX: (id: string) => `scenario-flow-history-item-${id}`,
  MODAL_HISTORY_BTN_CLOSE: 'scenario-flow-history-btn-close',
  MODAL_HISTORY_EXPORT_MD_PREFIX: (id: string) => `scenario-flow-history-export-md-${id}`,
  MODAL_HISTORY_EXPORT_CSV_PREFIX: (id: string) => `scenario-flow-history-export-csv-${id}`,
} as const;
