export const SCENARIO_FLOW_DETAIL_TEXT = {
  BACK_TO_FLOWS: 'Back to Flows',
  BACK_TO_SCENARIO_FLOWS: 'Back to Scenario Flows',
  RUN_TEST_BTN: 'Run Real Testing',
  RUN_TEST: 'Run Test',
  RUNNING_BTN: 'Executing Steps...',
  EXPORT_BTN: 'Export JSON',
  ADD_STEP_BTN: 'Add Step',
  ADD_FIRST_STEP: 'Add First Step',
  HISTORY_BTN: 'Run History',
  STEPS_HEADER: 'Chained Steps Sequence',
  RUNNER_HEADER: 'Live Test Runner & Inspector',
  TARGET_ENV_LABEL: 'Target Environment',
  TARGET_MODE_LABEL: 'Target Mode',
  MOCK_MODE: 'Internal Mock',
  LIVE_MODE: 'Live Backend',
  NO_STEPS_TITLE: 'No Steps in this Flow',
  NO_STEPS_DESC: 'Add your first API step to begin building the chained scenario.',
  EXTRACTORS_LABEL: 'Variable Extractors',
  ASSERTIONS_LABEL: 'Assertions',
  EXECUTION_SUMMARY: 'Execution Summary',
  LOADING_TITLE: 'Loading scenario flow details...',
  NOT_FOUND_TITLE: 'Flow Not Found',
  NOT_FOUND_DESC: 'The requested scenario flow does not exist or was deleted.',
  ACTIVE_STATUS: 'Active',
  DRAFT_STATUS: 'Draft',
  CROSS_PROJECT: 'Cross-Project Flow',
  DIAGRAM_FLOW: 'Diagram Flow',
  CLASSIC_LIST: 'Classic List',
  EDIT_FLOW_TOOLTIP: 'Edit Flow Title & Description',
  ADD_DESCRIPTION_PLACEHOLDER: '+ Add flow description...',
  DRAWER_TITLE: 'Live Runner & Step Inspector',
  DRAWER_SUBTITLE: 'Inspect sent payload, headers, response, and assertions',
  CLOSE_INSPECTOR: 'Close Inspector',
  RUNNING_LABEL: (seconds: string) => `RUNNING (${seconds}s)`,
  RUN_ITERATIONS_TITLE: 'Run Iterations',
  LOOP_TEST_BADGE: 'Loop Test',
  SINGLE_RUN: 'Run 1x (Single Run)',
  RUN_3X: 'Run 3x (Loop 3 times)',
  RUN_5X: 'Run 5x (Loop 5 times)',
  RUN_10X: 'Run 10x (Loop 10 times)',
  CUSTOM_N_LABEL: 'Run Custom N Times:',
  RUN_NX_BTN: (n: number) => `Run ${n}x`,
  HISTORY_MODAL_TITLE: 'Execution History',
  NO_EXECUTIONS: 'No executions recorded yet.',
  EXPORT_MD: 'Export MD',
  EXPORT_CSV: 'Export CSV',
  EDIT_FLOW_TITLE: 'Edit Scenario Flow',
  EDIT_FLOW_SUBTITLE: 'Update flow metadata, default execution environment, and shared variables.',
  SAVE_CHANGES: 'Save Changes',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',
} as const;
