export const SCENARIO_FLOW_DETAIL_SEMANTIC_ID = {
  CONTAINER: 'scenario-flow-detail-container',
  HEADER: 'scenario-flow-detail-header',
  BACK_BTN: 'scenario-flow-detail-back-btn',
  TITLE: 'scenario-flow-detail-title',
  EDIT_FLOW_BTN: 'scenario-flow-detail-edit-flow-btn',
  STATUS_BADGE: 'scenario-flow-detail-status-badge',
  PROJECT_BADGE: 'scenario-flow-detail-project-badge',
  VIEW_MODE_CANVAS: 'scenario-flow-detail-view-mode-canvas',
  VIEW_MODE_LIST: 'scenario-flow-detail-view-mode-list',
  ENV_SELECT: 'scenario-flow-detail-env-select',
  HISTORY_BTN: 'scenario-flow-detail-history-btn',
  EXPORT_BTN: 'scenario-flow-detail-export-btn',
  ADD_STEP_BTN: 'scenario-flow-detail-add-step-btn',
  RUN_BTN: 'scenario-flow-detail-run-btn',
  CANVAS_CONTAINER: 'scenario-flow-detail-canvas-container',
  CANVAS_TOOLBAR_ADD: 'scenario-flow-detail-canvas-toolbar-add',
  CANVAS_TOOLBAR_ARRANGE: 'scenario-flow-detail-canvas-toolbar-arrange',
  CANVAS_TOOLBAR_INSPECTOR: 'scenario-flow-detail-canvas-toolbar-inspector',
  STEPS_LIST: 'scenario-flow-detail-steps-list',
  STEP_CARD_PREFIX: (id: string | number) => `scenario-flow-step-card-${id}`,
  STEP_CARD_EDIT_PREFIX: (id: string | number) => `scenario-flow-step-edit-${id}`,
  STEP_CARD_DELETE_PREFIX: (id: string | number) => `scenario-flow-step-delete-${id}`,
  STEP_CARD_TOGGLE_PREFIX: (id: string | number) => `scenario-flow-step-toggle-${id}`,
  DRAWER: 'scenario-flow-detail-drawer',
  DRAWER_CLOSE_BTN: 'scenario-flow-detail-drawer-close-btn',
  EXECUTION_PANEL: 'scenario-flow-detail-execution-panel',
  STEP_INSPECTOR: 'scenario-flow-detail-step-inspector',
  MODAL_ADD_STEP: 'scenario-flow-detail-modal-add-step',
  MODAL_EDIT_FLOW: 'scenario-flow-detail-modal-edit-flow',
  MODAL_HISTORY: 'scenario-flow-detail-modal-history',
} as const;
