export const ENVIRONMENTS_TEXT = {
  TITLE: 'Project Environments',
  SUBTITLE: 'Configure mock server base URLs per environment',
  ADD_ENV_BTN: 'Add Environment',
  EMPTY_TITLE: 'No environments configured',
  EMPTY_DESC: 'Add environments like Local, Development, Staging, or Production to test mock responses against different base URLs.',
  MODAL_ADD_TITLE: 'Add Environment',
  MODAL_EDIT_TITLE: 'Edit Environment',
  LABEL_ENV_NAME: 'Environment Name *',
  LABEL_PUBLIC_URL: 'Public Mock Base URL *',
  LABEL_ORIGIN_URL: 'Proxy Origin Base URL',
  LABEL_ACTIVE_STATUS: 'Active Status',
  PLACEHOLDER_NAME: 'e.g. Staging, Production, Mobile-Dev',
  PLACEHOLDER_PUBLIC_URL: 'http://localhost:3000/api/mock/v1',
  PLACEHOLDER_ORIGIN_URL: 'https://api.staging.company.com',
  BTN_CANCEL: 'Cancel',
  BTN_CREATE: 'Create Environment',
  BTN_SAVE: 'Save Changes',
  CARD_PUBLIC_URL: 'Public Mock Base URL',
  CARD_ORIGIN_URL: 'Proxy Origin Base URL',
  DELETE_DIALOG_TITLE: 'Delete Environment?',
  DELETE_DIALOG_DESC: 'Are you sure you want to delete this environment configuration?',
  DELETE_DIALOG_CONFIRM: 'Delete',
} as const;
