export const DASHBOARD_SEMANTIC_ID = {
  CONTAINER: 'dashboard-container',
  HERO: 'dashboard-hero',
  CREATE_PROJECT_BTN: 'dashboard-create-project-btn',
  STATS_GRID: 'dashboard-stats-grid',
  DISTRIBUTION_BAR: 'dashboard-distribution-bar',
  RECENT_PROJECTS: 'dashboard-recent-projects',
  VIEW_ALL_PROJECTS_BTN: 'dashboard-view-all-projects-btn',
  PROJECT_ITEM: (id: string) => `dashboard-project-item-${id}`,
  CONFIGURED_ENDPOINTS: 'dashboard-configured-endpoints',
  ENDPOINT_ITEM: (id: string) => `dashboard-endpoint-item-${id}`,
  IMPORT_EXPORT_DIALOG: 'dashboard-import-export-dialog',
  IMPORT_DIALOG_CLOSE_BTN: 'dashboard-import-dialog-close-btn',
  EXPORT_BTN: 'dashboard-export-btn',
  IMPORT_FILE_INPUT: 'dashboard-import-file-input',
  IMPORT_MODE_MERGE_BTN: 'dashboard-import-mode-merge-btn',
  IMPORT_MODE_REPLACE_BTN: 'dashboard-import-mode-replace-btn',
  APPLY_IMPORT_BTN: 'dashboard-apply-import-btn',
} as const;
