export const DASHBOARD_TEXT = {
  TITLE: 'Engine Overview',
  SUBTITLE: 'Real-time overview of active mock projects, endpoints, and scenarios.',
  HERO_BADGE: 'MOCKING KITA STUDIO ENGINE',
  HERO_TITLE_PREFIX: 'Build predictable APIs ',
  HERO_TITLE_SUFFIX: 'before the backend exists.',
  HERO_DESCRIPTION: 'Create endpoints, define deterministic or weighted response rules, configure headers & parameters, and test multi-environment URLs instantly.',
  CREATE_PROJECT_BTN: 'Create Project',
  IMPORT_EXPORT_BTN: 'Import / Export JSON',
  RECENT_PROJECTS_TITLE: 'Recent Projects',
  CONFIGURED_ENDPOINTS_TITLE: 'Configured Endpoints',
  VIEW_ALL: 'View All',
  STATS_PROJECTS: 'PROJECTS',
  STATS_ENVIRONMENTS: 'ENVIRONMENTS',
  STATS_ENDPOINTS: 'ENDPOINTS',
  STATS_SCENARIOS: 'SCENARIOS',
  STATS_ACTIVE: 'Active',
  STATS_CONFIGURED: 'Configured',
  STATS_RESPS: 'Resps',
  HTTP_DISTRIBUTION_TITLE: 'HTTP Methods Distribution',
  HTTP_ENDPOINTS_TOTAL: 'Endpoints Total',
  IMPORT_EXPORT_DIALOG_TITLE: 'Import / Export Mock API Database',
  EXPORT_CONFIG_TITLE: 'Export Current Configuration',
  EXPORT_CONFIG_DESC: 'Download a full backup JSON containing all projects and API endpoints.',
  EXPORT_JSON_BTN: 'Export JSON',
  IMPORT_CONFIG_TITLE: 'Import Configuration File',
  IMPORT_DROP_LABEL: 'Click or drop a .json backup file here',
  IMPORT_SUPPORTS_LABEL: 'Supports JSON files exported from Mock API Studio',
  IMPORT_SUMMARY_TITLE: 'Import File Summary',
  IMPORT_MODE_LABEL: 'Import Mode',
  IMPORT_MODE_MERGE: 'Merge Data',
  IMPORT_MODE_MERGE_DESC: 'Appends data & prevents ID collisions',
  IMPORT_MODE_REPLACE: 'Replace All',
  IMPORT_MODE_REPLACE_DESC: 'Wipes all current data first',
  APPLY_IMPORT_BTN: 'Apply Import',
} as const;
