export const CHANGE_LOGS_ADMIN_TEXT = {
  TITLE: 'Change Logs',
  SUBTITLE: 'Riwayat audit aktivitas, modifikasi resource, dan proses impor data database.',
  REFRESH_BTN: 'Refresh',
  SEARCH_PLACEHOLDER: 'Search change logs...',
  ALL_ACTIONS: 'All Actions',
  ALL_PROJECTS: 'All Projects',
  SYSTEM_DATABASE: 'System / Database',
  DETAILS: 'Details',
  EMPTY_TITLE: 'No change logs found',
  EMPTY_DESC: 'Tidak ada riwayat aktivitas yang sesuai dengan kriteria pencarian/filter.',
  PREVIOUS: 'Previous',
  NEXT: 'Next',
  PAGE_LABEL: (page: number, total: number) => `Page ${page} of ${total}`,
  TOTAL_COUNT: (count: number) => `${count} entries found`,
  MODAL_TITLE: 'Change Log Details',
  LABEL_LOG_ID: 'Log ID',
  LABEL_TIMESTAMP: 'Timestamp',
  LABEL_OPERATOR: 'Operator',
  LABEL_ACTION: 'Action',
  LABEL_ENTITY_TYPE: 'Entity Type',
  LABEL_ENTITY_ID: 'Entity ID',
  LABEL_PROJECT_ID: 'Project ID',
  LABEL_DESCRIPTION: 'Description',
  LABEL_BEFORE_STATE: 'Before State',
  LABEL_AFTER_STATE: 'After State',
  LABEL_METADATA: 'Metadata',
  CLOSE_BTN: 'Close',
} as const;
