export const ASSISTANT_SEMANTIC_ID = {
  CONTAINER: 'assistant-page-container',
  HEADER: 'assistant-header',
  CHAT_TAB: 'assistant-tab-chat',
  INSOMNIA_TAB: 'assistant-tab-insomnia',
  OPENAPI_TAB: 'assistant-tab-openapi',
  SIMULATOR_TAB: 'assistant-tab-simulator',
  KNOWLEDGE_TAB: 'assistant-tab-knowledge',
  SESSIONS_SIDEBAR: 'assistant-sessions-sidebar',
  NEW_SESSION_BTN: 'assistant-new-session-btn',
  MESSAGES_CONTAINER: 'assistant-messages-container',
  INPUT_FORM: 'assistant-input-form',
  INPUT_TEXTAREA: 'assistant-input-textarea',
  SEND_BTN: 'assistant-send-btn',
  STOP_BTN: 'assistant-stop-btn',
  CLEAR_SESSION_BTN: 'assistant-clear-session-btn',
  MODEL_SELECTOR: 'assistant-model-selector',
  FLOATING_BTN: 'assistant-floating-btn',
  DRAWER_CONTAINER: 'assistant-drawer-container',
};
