export const PROJECT_DETAIL_SEMANTIC_ID = {
  CONTAINER: 'project-detail-container',
  HEADER: 'project-detail-header',
  TAB_LIST: 'project-detail-tabs',
  TAB_TRIGGER: (tab: string) => `project-detail-tab-${tab}`,
  METADATA_CARD: 'project-detail-metadata-card',
  BACK_BTN: 'project-detail-back-btn',
  DELETE_BTN: 'project-detail-delete-btn',
  EXPORT_IMPORT_BTN: 'project-detail-export-import-btn',
  OPENAPI_MODAL: 'project-detail-openapi-modal',
  OPENAPI_CLOSE_BTN: 'project-detail-openapi-close-btn',
  OPENAPI_TAB_EXPORT: 'project-detail-openapi-tab-export',
  OPENAPI_TAB_IMPORT: 'project-detail-openapi-tab-import',
  OPENAPI_EXPORT_BTN: 'project-detail-openapi-export-btn',
  OPENAPI_IMPORT_BTN: 'project-detail-openapi-import-btn',
  OPENAPI_CANCEL_BTN: 'project-detail-openapi-cancel-btn',
  OPENAPI_FILE_INPUT: 'project-detail-openapi-file-input',
  OPENAPI_JSON_TEXTAREA: 'project-detail-openapi-json-textarea',
  OPENAPI_MODE_BTN: (mode: string) => `project-detail-openapi-mode-${mode}`,
} as const;

