export const PROJECT_DETAIL_TEXT = {
  TITLE: 'Project Overview',
  SUBTITLE: 'Manage project endpoints, environment configurations, and rules.',
  BACK_TO_PROJECTS: 'Back to Projects',
  TAB_APIS: 'API Collections',
  TAB_ENVIRONMENTS: 'Environments',
  TAB_SCENARIO_FLOWS: 'Flow Scenarios',
  TAB_DATA_SHEETS: 'Data Sheets',
  TAB_OVERVIEW: 'Project Information',
  METADATA_TITLE: 'Project Metadata',
  METADATA_PROJECT_ID: 'Project ID',
  METADATA_CREATED_AT: 'Created At',
  METADATA_LAST_UPDATED: 'Last Updated',
  CREATED_DATE_LABEL: 'Created Date',
  NO_DESCRIPTION: 'No project description configured.',
  STATUS_ACTIVE: 'Active',
  STATUS_DISABLED: 'Disabled',
  TITLE_DELETE_PROJECT: 'Delete Project',
  EXPORT_IMPORT_JSON_BTN: 'Export / Import JSON',
  LOADING_TITLE: 'Loading project...',
  LOADING_DESC: 'Fetching project data from the server.',
  NOT_FOUND_TITLE: 'Project Not Found',
  NOT_FOUND_DESC: 'The requested project ID does not exist or was deleted.',
  OPENAPI_MODAL_TITLE: 'OpenAPI / Swagger Docs',
  OPENAPI_MODAL_DESC: (projectName: string) => `Export or Import OpenAPI 3.0 / Swagger JSON specifications specifically for ${projectName}.`,
  OPENAPI_TAB_EXPORT: 'Export OpenAPI',
  OPENAPI_TAB_IMPORT: 'Import OpenAPI',
  OPENAPI_EXPORT_FORMAT_LABEL: 'Export Format: OpenAPI 3.0.3 (JSON)',
  OPENAPI_EXPORT_INCLUDES_DESC: 'Includes all collections, endpoints, request parameters, and response scenarios for this project.',
  OPENAPI_UPLOAD_OR_PASTE_LABEL: 'Upload File or Paste OpenAPI JSON',
  OPENAPI_PLACEHOLDER_JSON: 'Paste OpenAPI / Swagger JSON spec here...',
  OPENAPI_BTN_EXPORT: 'Export OpenAPI',
  OPENAPI_BTN_EXPORTING: 'Exporting...',
  OPENAPI_BTN_IMPORT: 'Import OpenAPI',
  OPENAPI_BTN_IMPORTING: 'Importing...',
  BTN_CANCEL: 'Cancel',
  IMPORT_MODE_LABEL: 'Import Mode',
  IMPORT_MODE_UPSERT_LABEL: 'Upsert',
  IMPORT_MODE_UPSERT_BADGE: 'Default',
  IMPORT_MODE_UPSERT_DESC: 'Update existing & insert new',
  IMPORT_MODE_MERGE_LABEL: 'Merge',
  IMPORT_MODE_MERGE_DESC: 'Add all endpoints as new',
  IMPORT_MODE_REPLACE_LABEL: 'Replace',
  IMPORT_MODE_REPLACE_DESC: 'Overwrite all endpoints',
  OPENAPI_LOADING_EXPORT_TITLE: 'Preparing OpenAPI export',
  OPENAPI_LOADING_EXPORT_DESC: 'Please wait while the project specification is generated.',
  OPENAPI_LOADING_IMPORT_TITLE: 'Importing Swagger JSON',
  OPENAPI_LOADING_IMPORT_DESC: 'Large files are processed in smaller batches. Please keep this window open.',
} as const;

