export const DATA_SHEET_TEXT = {
  TITLE: 'Data Sheets',
  SUBTITLE: 'Manage array-based datasets (emails, phone numbers, test data) to use dynamically across Scenario Flows and Request Scenarios.',
  CREATE_BUTTON: 'Create Data Sheet',
  SEARCH_PLACEHOLDER: 'Search data sheets by name, slug, or category...',
  ALL_PROJECTS: 'All Projects',
  ALL_CATEGORIES: 'All Categories',
  GLOBAL_SHEET: 'Global (All Projects)',
  EMPTY_STATE_TITLE: 'No Data Sheets Found',
  EMPTY_STATE_SUBTITLE: 'Get started by creating your first dataset pool to use as dynamic parameters in flows and scenarios.',
  FORMAT_LIST: 'List (Values)',
  FORMAT_TABLE: 'Table (Records)',
  CONFIRM_DELETE_TITLE: 'Delete Data Sheet',
  CONFIRM_DELETE_DESC: (name: string) => `Are you sure you want to delete "${name}"? This action cannot be undone.`,
  EDIT_BTN: 'Edit Data Sheet',
  PREVIEW_BTN: 'Preview Dataset',
  DELETE_BTN: 'Delete',
  ITEMS_COUNT_SUFFIX: (count: number) => `${count} items`,
  COLUMNS_COUNT_SUFFIX: (count: number) => `${count} cols`,

  // Modal Form
  MODAL_TITLE_CREATE: 'Create Data Sheet',
  MODAL_TITLE_EDIT: 'Edit Data Sheet',
  MODAL_SUBTITLE: 'Configure dataset array for parameterized testing & dynamic scenarios',
  SECTION_DETAILS: '1. Data Sheet Details',
  NAME_LABEL: 'Data Sheet Name',
  NAME_PLACEHOLDER: 'e.g. Valid Customer Emails, Promo Codes',
  CODE_LABEL: 'Code Identifier (Slug)',
  CODE_PLACEHOLDER: 'e.g. customer_emails, promo_codes',
  PROJECT_LABEL: 'Target Project',
  CATEGORY_LABEL: 'Category',
  DESC_LABEL: 'Description (Optional)',
  DESC_PLACEHOLDER: 'Brief context of what data this sheet provides...',
  SECTION_PAYLOAD: '2. Data Format & Payload',
  FORMAT_LIST_TITLE: 'List (Array of Primitive Values)',
  FORMAT_LIST_SUB: 'e.g. [ "user1@mail.com", "user2@mail.com" ]',
  FORMAT_TABLE_TITLE: 'Table (Array of Key-Value Objects)',
  FORMAT_TABLE_SUB: 'e.g. [ { "id": "1", "role": "admin" }, ... ]',
  TAB_LINES: 'Lines / Simple List',
  TAB_JSON: 'Direct JSON Array',
  LINES_PLACEHOLDER_LIST: 'Enter one value per line, e.g.:\njohn@example.com\nsarah@example.com\nadmin@test.io',
  LINES_PLACEHOLDER_TABLE: 'Enter comma or pipe separated records, e.g.:\nemail,role,status\njohn@example.com,admin,active\nsarah@example.com,user,pending',
  JSON_PLACEHOLDER: '[\n  "item1",\n  "item2"\n]',
  BTN_GENERATE_MOCK: 'Generate Mock Examples',
  BTN_UPLOAD_FILE: 'Upload CSV / TXT',
  ELEMENTS_COUNT: (count: number) => `Total Elements: ${count}`,
  BTN_SAVE: 'Save Data Sheet',
  BTN_SAVING: 'Saving...',
  BTN_CANCEL: 'Cancel',
  ERR_NAME_REQUIRED: 'Name is required.',
  ERR_CODE_REQUIRED: 'Code identifier is required.',
  ERR_INVALID_CODE_PATTERN: 'Code can only contain lowercase alphanumeric characters, underscores, dashes, and dots',
  ERR_EMPTY_DATA: 'Data array cannot be empty. Please provide at least one element.',
  ERR_INVALID_JSON: 'Invalid JSON syntax. Please check the JSON format.',
  ERR_MUST_BE_ARRAY: 'JSON payload must be an array ([ ... ]).',
  ERR_FAILED_FILE_READ: 'Failed to read file',
  ERR_INVALID_DATA_FORMAT: 'Invalid data format',
  ERR_FAILED_SAVE: 'Failed to save data sheet',
  REMOVED_DUPLICATES: (removed: number) => `Removed ${removed} duplicate ${removed === 1 ? 'entry' : 'entries'}`,

  // Modal Form Additional
  FORMAT_LABEL: 'Dataset Format',
  DATA_VALUES_LABEL: 'Data Values',
  VARIABLE_SYNTAX_LABEL: 'Variable Syntax:',
  OR_LABEL: 'or',
  CATEGORY_PLACEHOLDER: 'e.g. Contact, Authentication, Payment',
  LINES_HINT: 'Enter one value per line. Empty lines are automatically ignored.',
  JSON_HINT: 'Must be a valid JSON array format.',
  DEDUPLICATE_BTN: 'Deduplicate',
  DEDUPLICATE_TOOLTIP: 'Remove duplicate values',
  FORMAT_JSON_BTN: 'Format',
  FORMAT_JSON_TOOLTIP: 'Prettify JSON syntax',
  CLEAR_DATA_TOOLTIP: 'Clear all data',
  FILE_UPLOAD_TOOLTIP: 'Import data from CSV, TXT, or JSON file',

  // Preview Modal
  PREVIEW_TITLE: 'Preview Data Sheet',
  PREVIEW_SEARCH_PLACEHOLDER: 'Search records in this dataset...',
  PREVIEW_COPY_TAG: 'Copy Variable Tag',
  PREVIEW_TAG_COPIED: 'Copied!',
  PREVIEW_EMPTY_SEARCH: 'No records match your search filter.',
  PREVIEW_INDEX_COL: '#',
  PREVIEW_TOTAL: (count: number) => `${count} total entries`,

  // Card & General
  LOADING_DATA_SHEETS: 'Loading data sheets...',
  NO_DESCRIPTION: 'No description provided',
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'Inactive',
  INSPECT_TOOLTIP: 'Inspect Data Sheet',
  EDIT_TOOLTIP: 'Edit Data Sheet',
  DELETE_TOOLTIP: 'Delete Data Sheet',
  ITEMS_COUNT: (count: number) => `${count} ${count === 1 ? 'item' : 'items'}`,
  ITEMS_STORED: (count: number) => `${count} items stored`,
  DATA_PREVIEW: 'Data Preview',
  EMPTY_DATASET: 'Empty dataset',
  MORE_ITEMS_CLICK: (count: number) => `+${count} more (click to view)`,
  TOKENS_LABEL: 'Tokens:',
  EMPTY_STATE_CREATE_BTN: 'Create Data Sheet',
  CLICK_TO_COPY_TOKEN: 'Click to copy variable token',
} as const;

export const DATA_SHEET_CATEGORIES = [
  'General',
  'Authentication',
  'Contact',
  'User Profile',
  'Payment & Billing',
  'Product & Catalog',
  'Location & Address',
];
