export const DATA_SHEET_SEMANTIC_ID = {
  CONTAINER: 'data-sheets-container',
  HEADER: 'data-sheets-header',
  TITLE: 'data-sheets-title',
  CREATE_BTN: 'data-sheets-create-btn',
  SEARCH_INPUT: 'data-sheets-search-input',
  PROJECT_FILTER: 'data-sheets-project-filter',
  CATEGORY_FILTER: 'data-sheets-category-filter',
  GRID: 'data-sheets-grid',
  EMPTY_STATE: 'data-sheets-empty-state',
  EMPTY_STATE_CREATE_BTN: 'data-sheets-empty-create-btn',
  CARD_PREFIX: (id: string) => `data-sheet-card-${id}`,
  CARD_PREVIEW_BTN_PREFIX: (id: string) => `data-sheet-card-preview-btn-${id}`,
  CARD_EDIT_BTN_PREFIX: (id: string) => `data-sheet-card-edit-btn-${id}`,
  CARD_DELETE_BTN_PREFIX: (id: string) => `data-sheet-card-delete-btn-${id}`,
  CARD_TOGGLE_PREFIX: (id: string) => `data-sheet-card-toggle-${id}`,
  MODAL_FORM: 'data-sheet-modal-form',
  MODAL_FORM_INPUT_NAME: 'data-sheet-modal-input-name',
  MODAL_FORM_INPUT_CODE: 'data-sheet-modal-input-code',
  MODAL_FORM_SELECT_PROJECT: 'data-sheet-modal-select-project',
  MODAL_FORM_SELECT_CATEGORY: 'data-sheet-modal-select-category',
  MODAL_FORM_INPUT_DESC: 'data-sheet-modal-input-desc',
  MODAL_FORM_SELECT_FORMAT: 'data-sheet-modal-select-format',
  MODAL_FORM_FORMAT_LIST_BTN: 'data-sheet-modal-format-list-btn',
  MODAL_FORM_FORMAT_TABLE_BTN: 'data-sheet-modal-format-table-btn',
  MODAL_FORM_TAB_LINES: 'data-sheet-modal-tab-lines',
  MODAL_FORM_TAB_JSON: 'data-sheet-modal-tab-json',
  MODAL_FORM_TEXTAREA_LINES: 'data-sheet-modal-textarea-lines',
  MODAL_FORM_TEXTAREA_JSON: 'data-sheet-modal-textarea-json',
  MODAL_FORM_FILE_INPUT: 'data-sheet-modal-file-input',
  MODAL_FORM_BTN_GENERATE_MOCK: 'data-sheet-modal-btn-generate-mock',
  MODAL_FORM_BTN_UPLOAD: 'data-sheet-modal-btn-upload',
  MODAL_FORM_BTN_DEDUPLICATE: 'data-sheet-modal-btn-deduplicate',
  MODAL_FORM_BTN_FORMAT_JSON: 'data-sheet-modal-btn-format-json',
  MODAL_FORM_BTN_CLEAR: 'data-sheet-modal-btn-clear',
  MODAL_FORM_BTN_SUBMIT: 'data-sheet-modal-btn-submit',
  MODAL_FORM_BTN_CANCEL: 'data-sheet-modal-btn-cancel',
  MODAL_FORM_BTN_CLOSE: 'data-sheet-modal-btn-close',
  MODAL_PREVIEW: 'data-sheet-modal-preview',
  MODAL_PREVIEW_CLOSE_BTN: 'data-sheet-preview-close-btn',
  MODAL_PREVIEW_SEARCH_INPUT: 'data-sheet-preview-search-input',
  MODAL_PREVIEW_EDIT_BTN: 'data-sheet-preview-edit-btn',
  MODAL_PREVIEW_COPY_BTN: 'data-sheet-preview-copy-btn',
} as const;
