export const PROJECTS_TEXT = {
  TITLE: 'Projects Workspace',
  SUBTITLE: 'Organize mock API definitions and response scenarios by project',
  ADD_PROJECT_BTN: 'Add Project',
  SEARCH_PLACEHOLDER: 'Search projects...',
  EMPTY_TITLE: 'No projects found',
  EMPTY_DESC: 'Create your first mock project to start adding API definitions.',
  EMPTY_SEARCH_DESC: 'No projects matching',
  CREATE_PROJECT_BTN: 'Create Project',
  ACTION_OPEN_DETAIL: 'Open Detail',
  ACTION_EDIT_DETAILS: 'Edit Details',
  ACTION_DUPLICATE: 'Duplicate',
  ACTION_RESTORE: 'Restore',
  ACTION_PERMANENTLY_DELETE: 'Permanently Delete',
  ACTION_SOFT_DELETE: 'Soft Delete',
  TABLE_COL_NAME: 'Project Name',
  TABLE_COL_STATUS: 'Status',
  TABLE_COL_CREATED: 'Created Date',
  TABLE_COL_ACTIONS: 'Actions',
  MODAL_ADD_TITLE: 'Add New Project',
  MODAL_EDIT_TITLE: 'Edit Project',
  LABEL_PROJECT_NAME: 'Project Name *',
  LABEL_DESCRIPTION: 'Description',
  LABEL_ACTIVE_STATUS: 'Active Status',
  PLACEHOLDER_NAME: 'e.g. E-Commerce Platform API',
  PLACEHOLDER_DESC: 'Brief summary of what this project provides...',
  BTN_CANCEL: 'Cancel',
  BTN_CREATE: 'Create Project',
  BTN_SAVE: 'Save Changes',
  DELETE_DIALOG_TITLE: 'Permanently Delete Project?',
  DELETE_DIALOG_DESC_PREFIX: 'Are you sure you want to permanently delete',
  DELETE_DIALOG_DESC_SUFFIX: '? All associated API definitions and scenarios will be removed permanently.',
  DELETE_DIALOG_CONFIRM: 'Permanently Delete',
  STATUS_ALL: 'All Status',
  STATUS_ACTIVE: 'Active',
  STATUS_DISABLED: 'Disabled',
  STATUS_DELETED: 'Deleted',
  VIEW_GRID: 'Grid View',
  VIEW_TABLE: 'Table View',
  ENDPOINTS_COUNT_SUFFIX: 'Endpoints',
  NO_DESCRIPTION: 'No description provided.',
  LABEL_PIC_PROJECT: 'Person In Charge (PIC)',
  PLACEHOLDER_PIC_PROJECT: 'Pilih PIC project...',
} as const;

