export const PROJECTS_SEMANTIC_ID = {
  CONTAINER: 'projects-container',
  HEADER: 'projects-header',
  FILTER_BAR: 'projects-filter-bar',
  SEARCH_INPUT: 'projects-search-input',
  ADD_PROJECT_BTN: 'projects-add-btn',
  PROJECT_GRID: 'projects-grid',
  PROJECT_TABLE: 'projects-table',
  FORM_MODAL: 'projects-form-modal',
  FORM_CLOSE_BTN: 'projects-form-close-btn',
  FORM_INPUT_NAME: 'projects-form-input-name',
  FORM_TEXTAREA_DESC: 'projects-form-textarea-desc',
  FORM_CHECKBOX_STATUS: 'projects-form-checkbox-status',
  FORM_FOOTER: 'projects-form-footer',
  FORM_BTN_SUBMIT: 'projects-form-btn-submit',
  FORM_BTN_CANCEL: 'projects-form-btn-cancel',
  STATUS_FILTER_BTN: (status: string) => `projects-status-filter-${status.toLowerCase()}`,
  SORT_SELECT: 'projects-sort-select',
  VIEW_MODE_GRID_BTN: 'projects-view-mode-grid-btn',
  VIEW_MODE_TABLE_BTN: 'projects-view-mode-table-btn',
  CARD_ITEM: (id: string) => `project-card-${id}`,
  CARD_DROPDOWN_TRIGGER: (id: string) => `project-card-dropdown-trigger-${id}`,
  CARD_ACTION_OPEN: (id: string) => `project-card-action-open-${id}`,
  CARD_ACTION_EDIT: (id: string) => `project-card-action-edit-${id}`,
  CARD_ACTION_DUPLICATE: (id: string) => `project-card-action-duplicate-${id}`,
  CARD_ACTION_RESTORE: (id: string) => `project-card-action-restore-${id}`,
  CARD_ACTION_SOFT_DELETE: (id: string) => `project-card-action-soft-delete-${id}`,
  CARD_ACTION_PERM_DELETE: (id: string) => `project-card-action-perm-delete-${id}`,
  TABLE_ROW: (id: string) => `project-table-row-${id}`,
  TABLE_VIEW_BTN: (id: string) => `project-table-view-btn-${id}`,
  TABLE_EDIT_BTN: (id: string) => `project-table-edit-btn-${id}`,
} as const;

