export const ENVIRONMENTS_SEMANTIC_ID = {
  CONTAINER: 'environments-container',
  PAGE_TITLE: 'environments-page-title',
  CREATE_BTN: 'environments-create-btn',
  SEARCH_INPUT: 'environments-search-input',
  PROJECT_FILTER: 'environments-project-filter',
  GRID: 'environments-grid',
  EMPTY_STATE: 'environments-empty-state',
  CARD: (id: string) => `environment-card-${id}`,
  EDIT_BTN: (id: string) => `environment-edit-btn-${id}`,
  DELETE_BTN: (id: string) => `environment-delete-btn-${id}`,
  STATUS_SWITCH: (id: string) => `environment-status-switch-${id}`,
  CARD_COPY_URL_BTN: (id: string) => `environment-card-copy-url-${id}`,
  CARD_TOGGLE_VARS_BTN: (id: string) => `environment-card-toggle-vars-${id}`,
  CARD_TOGGLE_STAGES_BTN: (id: string) => `environment-card-toggle-stages-${id}`,
  CARD_VAR_ROW: (id: string, key: string) => `environment-card-var-row-${id}-${key}`,
  FORM_MODAL: 'environment-form-modal',
  FORM_CLOSE_BTN: 'environment-form-close-btn',
  FORM_NAME_INPUT: 'environment-form-name-input',
  FORM_PROJECT_SELECT: 'environment-form-project-select',
  FORM_TYPE_SELECT: 'environment-form-type-select',
  FORM_BASE_URL_INPUT: 'environment-form-base-url-input',
  FORM_BASEURL_MODE_BTN: 'environment-form-baseurl-mode-btn',
  FORM_VARS_MODE_BTN: 'environment-form-vars-mode-btn',
  FORM_SWITCH_BASEURL: 'environment-form-switch-baseurl',
  FORM_SWITCH_STATUS: 'environment-form-switch-status',
  FORM_STAGE_INPUT: (stage: string) => `environment-form-stage-input-${stage.toLowerCase()}`,
  FORM_STAGE_CLEAR_BTN: (stage: string) => `environment-form-stage-clear-${stage.toLowerCase()}`,
  FORM_TOGGLE_VARS_SECTION_BTN: 'environment-form-toggle-vars-section-btn',
  FORM_PRESET_APIKEY_BTN: 'environment-form-preset-apikey-btn',
  FORM_PRESET_BEARER_BTN: 'environment-form-preset-bearer-btn',
  FORM_PRESET_BASICAUTH_BTN: 'environment-form-preset-basicauth-btn',
  FORM_ADD_VAR_BTN: 'environment-form-add-var-btn',
  FORM_CLEAR_VARS_BTN: 'environment-form-clear-vars-btn',
  FORM_VAR_KEY_INPUT: (id: string) => `environment-form-var-key-${id}`,
  FORM_VAR_VALUE_INPUT: (id: string) => `environment-form-var-value-${id}`,
  FORM_VAR_SHOW_VALUE_BTN: (id: string) => `environment-form-var-show-value-${id}`,
  FORM_VAR_TYPE_SELECT: (id: string) => `environment-form-var-type-${id}`,
  FORM_VAR_TOGGLE_BTN: (id: string) => `environment-form-var-toggle-${id}`,
  FORM_VAR_DELETE_BTN: (id: string) => `environment-form-var-delete-${id}`,
  FORM_SUBMIT_BTN: 'environment-form-submit-btn',
  FORM_CANCEL_BTN: 'environment-form-cancel-btn',
} as const;
