export const ENVIRONMENTS_TEXT = {
  TITLE: 'Environments',
  SUBTITLE: 'Manage environment configurations and base URLs for your projects.',
  CREATE_BUTTON: 'Create Environment',
  EDIT_BUTTON: 'Edit Environment',
  SEARCH_PLACEHOLDER: 'Search environments by name or base URL...',
  ALL_PROJECTS: 'All Projects',
  NO_ENVIRONMENTS: 'No environments found.',
  NO_ENVIRONMENTS_SUBTITLE: 'Get started by creating a new environment configuration or import from OpenAPI.',
  DELETE_CONFIRM_TITLE: 'Delete Environment',
  DELETE_CONFIRM_MESSAGE: 'Are you sure you want to delete this environment? This action cannot be undone.',
  DELETE_CONFIRM_BTN: 'Delete',

  // Modal Text
  MODAL_TITLE_CREATE: 'Configure Environment',
  MODAL_TITLE_EDIT: 'Edit Environment',
  MODAL_SUBTITLE: 'Configure multi-stage base URLs and runtime environment variables',
  MULTI_STAGE_SECTION_TITLE: 'Base URL Multi-Stage Routing',
  MULTI_STAGE_SECTION_DESC: 'Specify backend target URLs for each stage. Scenario flows can seamlessly switch between stages without editing paths.',
  BASE_URL_TOGGLE_LABEL: 'Enable Base URL Multi-Stage Routing',
  BASE_URL_TOGGLE_DESC: 'When enabled, this environment routes API requests across stages (Dev, Test, Staging, Prod).',
  VARIABLES_SECTION_TITLE: 'Custom Runtime Variables',
  VARIABLES_SECTION_DESC: 'Add tokens, keys, passwords, and custom data available in scenario flows as {{variable_name}}',
  BTN_ADD_VARIABLE: 'Add Variable',
  BTN_CLEAR_ALL: 'Clear All',
  TABLE_COL_KEY: 'Variable Key',
  TABLE_COL_TYPE: 'Type',
  TABLE_COL_VALUE: 'Initial Value',
  TABLE_COL_DESC: 'Description',
  TABLE_COL_ACTIONS: 'Actions',
  NO_VARS_EMPTY_TITLE: 'No custom variables added',
  NO_VARS_EMPTY_DESC: 'Click "Add Variable" to store auth tokens, API keys, or dynamic flow parameters.',
  BTN_SAVE: 'Save Environment',
  BTN_SAVING: 'Saving...',
  BTN_CANCEL: 'Cancel',

  // Card Text
  CARD_ENV_STAGES: 'Environment Stages',
  CARD_CONFIGURED: 'configured',
  CARD_LOCAL_MOCK: 'local mock',
  CARD_BASE_URL_NOT_CONFIGURED: 'Base URL not configured',
  CARD_COPIED: 'Copied!',
  CARD_COPY_URL: 'Copy Base URL',
  CARD_EXPAND_VARS: 'View Variables',
  CARD_COLLAPSE_VARS: 'Hide Variables',
  CARD_BASE_URL: 'Base URL',
  CARD_VARIABLES: 'Variables',
  CARD_LOCAL_MOCK_TITLE: 'LOCAL: Auto handled by Mock Engine',
  CARD_NOT_CONFIGURED: 'Not configured',
  CARD_INTERNAL_PROXY_LABEL: 'Mock Server Proxy (Internal)',
  CARD_SHOW_LESS_STAGES: 'Show fewer stages',
  CARD_SHOW_MORE_STAGES: (count: number) => `Show ${count} more stages`,
  CARD_NO_STAGES_CONFIGURED: 'No stage values configured yet',
  CARD_CUSTOM_VARIABLES: (count: number) => `Custom Variables (${count})`,
  CARD_EDIT_MATRIX: 'Edit Matrix',
  CARD_DELETE_BTN: 'Delete',
  COPIED_TO_CLIPBOARD: (label: string) => `${label} copied to clipboard`,

  // Form Modal Additional
  FORM_BASE_URL_ENDPOINT_TITLE: 'Base URL Service Endpoint',
  FORM_BASE_URL_ENDPOINT_DESC: 'Base URL for routing API calls to target server (Dev, Testing, Staging, Prod). LOCAL is auto-handled by Mock API Studio.',
  FORM_GENERAL_CONFIG_TITLE: 'General Variables & Config',
  FORM_GENERAL_CONFIG_DESC: 'Configuration variables, secret keys, or tokens per stage (all 5 stages including LOCAL can be configured).',
  FORM_MULTI_STAGE_MATRIX_TITLE: 'Multi-Environment Matrix Values (5 Stages)',
  FORM_MULTI_STAGE_MATRIX_DESC_BASE: 'Define target Base URL servers for each testing and deployment stage.',
  FORM_MULTI_STAGE_MATRIX_DESC_VARS: 'Define variable and configuration values for each stage.',
  FORM_LOCAL_MOCK_AUTO_LABEL: 'Auto Mock',
  FORM_LOCAL_MOCK_PLACEHOLDER: 'Auto-handled by local Mock API Studio (http://localhost:PORT)',
  FORM_INTERNAL_PROXY_BADGE: 'Internal Proxy',
  FORM_BASE_URL_PATTERN_STRONG: 'Base URL Design Pattern:',
  FORM_BASE_URL_PATTERN_DESC: 'Scenario flow calls on the LOCAL stage are always routed to the internal Mock Engine. When run on DEVELOPMENT, STAGING, or PRODUCTION, the runner automatically uses the corresponding base URL defined above.',
  FORM_CUSTOM_VARS_TITLE: (count: number) => `Custom Variables & Secrets (Optional: ${count})`,
  FORM_CLICK_TO_HIDE: '(Click to hide)',
  FORM_CLICK_TO_SHOW: '(Click to show)',
  FORM_PRESET_API_KEY: '+ API Key',
  FORM_PRESET_BEARER: '+ Bearer',
  FORM_PRESET_BASIC_AUTH: '+ Basic Auth',
  FORM_COL_USE: 'Use',
  FORM_VARS_COUNT_LABEL: (count: number) => `${count} variables`,
  FORM_TOOLTIP_CLEAR: 'Clear',
  FORM_TOOLTIP_REMOVE_VAR: 'Remove variable',
  FORM_TOOLTIP_HIDE_VALUE: 'Hide value',
  FORM_TOOLTIP_SHOW_VALUE: 'Show value',
  FORM_TOOLTIP_MASKED_SECRET: 'Masked Secret',
  FORM_TOOLTIP_PLAIN_TEXT: 'Plain Text',

  STAGE_CONFIG: {
    LOCAL: {
      label: 'LOCAL',
      badgeColor: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800',
      placeholder: 'Otomatis dihandle Mock Engine (http://localhost:PORT)',
      helper: 'Dikelola otomatis oleh internal mock engine',
    },
    DEVELOPMENT: {
      label: 'DEVELOPMENT',
      badgeColor: 'bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400 border-blue-200 dark:border-blue-800',
      placeholder: 'https://dev-api.example.com',
      helper: 'Endpoint untuk pengembangan & dev integration',
    },
    TESTING: {
      label: 'TESTING',
      badgeColor: 'bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-400 border-amber-200 dark:border-amber-800',
      placeholder: 'https://test-api.example.com',
      helper: 'Endpoint untuk QA / automated test server',
    },
    STAGING: {
      label: 'STAGING',
      badgeColor: 'bg-purple-50 text-purple-700 dark:bg-purple-950/50 dark:text-purple-400 border-purple-200 dark:border-purple-800',
      placeholder: 'https://staging-api.example.com',
      helper: 'Endpoint pre-production mirip production',
    },
    PRODUCTION: {
      label: 'PRODUCTION',
      badgeColor: 'bg-rose-50 text-rose-700 dark:bg-rose-950/50 dark:text-rose-400 border-rose-200 dark:border-rose-800',
      placeholder: 'https://api.example.com',
      helper: 'Live production API endpoint',
    },
  },

  FORM: {
    NAME_LABEL: 'Environment Name',
    NAME_PLACEHOLDER: 'e.g., Development Server, Staging API',
    PROJECT_LABEL: 'Target Project',
    SELECT_PROJECT: 'Select a project',
    TYPE_LABEL: 'Environment Type',
    VARIABLES_LABEL: 'Environment Variables & Values',
    VARIABLES_SUBTITLE: 'Define key-value pairs (baseUrl, apiKey, user, password, tokens) available in scenario flows and requests via {{key}}.',
    ADD_VARIABLE: 'Add Variable',
    NO_VARIABLES: 'No variables configured yet. Click "Add Variable" to add baseUrl, API keys, credentials, etc.',
    BASE_URL_LABEL: 'Base URL',
    BASE_URL_PLACEHOLDER: 'https://api-dev.example.com',
    STATUS_LABEL: 'Active Status',
    SAVE: 'Save Environment',
    CANCEL: 'Cancel',
  },
  TOAST: {
    CREATE_SUCCESS: 'Environment created successfully',
    UPDATE_SUCCESS: 'Environment updated successfully',
    DELETE_SUCCESS: 'Environment deleted successfully',
    COPIED_URL: 'Base URL copied to clipboard',
    COPIED_VALUE: 'Variable value copied to clipboard',
  },
} as const;
