export const ENVIRONMENTS_TEXT = {
  TITLE: 'Environments',
  SUBTITLE: 'Manage environment configurations and base URLs for your projects.',
  CREATE_BUTTON: 'Create Environment',
  EDIT_BUTTON: 'Edit Environment',
  SEARCH_PLACEHOLDER: 'Search environments by name or base URL...',
  ALL_PROJECTS: 'All Projects',
  NO_ENVIRONMENTS: 'No environments found.',
  NO_ENVIRONMENTS_SUBTITLE: 'Get started by creating a new environment configuration or import from OpenAPI.',
  DELETE_CONFIRM_TITLE: 'Delete Environment',
  DELETE_CONFIRM_MESSAGE: 'Are you sure you want to delete this environment? This action cannot be undone.',
  FORM: {
    NAME_LABEL: 'Environment Name',
    NAME_PLACEHOLDER: 'e.g., Development Server, Staging API',
    PROJECT_LABEL: 'Target Project',
    SELECT_PROJECT: 'Select a project',
    TYPE_LABEL: 'Environment Type',
    VARIABLES_LABEL: 'Environment Variables & Values',
    VARIABLES_SUBTITLE: 'Define key-value pairs (baseUrl, apiKey, user, password, tokens) available in scenario flows and requests via {{key}}.',
    ADD_VARIABLE: 'Add Variable',
    NO_VARIABLES: 'No variables configured yet. Click "Add Variable" to add baseUrl, API keys, credentials, etc.',
    BASE_URL_LABEL: 'Base URL',
    BASE_URL_PLACEHOLDER: 'https://api-dev.example.com',
    STATUS_LABEL: 'Active Status',
    SAVE: 'Save Environment',
    CANCEL: 'Cancel',
  },
  TOAST: {
    CREATE_SUCCESS: 'Environment created successfully',
    UPDATE_SUCCESS: 'Environment updated successfully',
    DELETE_SUCCESS: 'Environment deleted successfully',
    COPIED_URL: 'Base URL copied to clipboard',
    COPIED_VALUE: 'Variable value copied to clipboard',
  },
};
