export const REQUEST_SCENARIO_EDITOR_TEXT = {
  TITLE_CREATE: 'Create Request Scenario',
  TITLE_EDIT_PREFIX: 'Edit Scenario:',
  SUBTITLE: 'Konfigurasi aturan pencocokan parameter, header, dan body payload untuk endpoint mock API.',
  BTN_SAVE_CHANGES: 'Save Changes',
  BTN_CREATE_SCENARIO: 'Create Scenario',
  BTN_CANCEL: 'Cancel',
  LABEL_NAME: 'Scenario Name',
  PLACEHOLDER_NAME: 'e.g. Success 200 with Active Status',
  LABEL_PRIORITY: 'Priority',
  LABEL_STATUS: 'Active Scenario',
  LABEL_MATCH_STRATEGY: 'Match Strategy (Rule Combination)',
  STRATEGY_ALL: 'Match ALL Parameters (AND - Semua parameter harus cocok)',
  STRATEGY_ANY: 'Match ANY Parameter (OR - Salah satu parameter cocok)',
  QUERY_PARAMS_TITLE: 'Query Parameters Matching',
  HEADERS_TITLE: 'Headers Matching',
  BODY_TITLE: 'Request Body Matching',
  BODY_TYPE_LABEL: 'Body Type:',
  BODY_NONE_NOTICE: 'Skenario ini tidak mengevaluasi request body (Body Type: None).',
  LOADING_SCENARIO_DETAILS: 'Loading scenario details...',
  DEFAULT_SCENARIO_NAME: 'Request Scenario',
  BASIC_CARD_TITLE: 'Basic Configuration & Matchmaking Strategy',
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'Inactive',
  NAME_HINT: 'Identitas unik untuk mendeskripsikan kondisi skenario request ini.',
  PRIORITY_HINT: 'Prioritas evaluasi (nilai lebih tinggi dievaluasi duluan).',
  MATCH_STRATEGY_HINT: 'Pilih apakah seluruh kriteria harus cocok (AND) atau minimal satu cocok (OR).',
  ENV_VARS_BTN: 'Env Vars',
  DATA_SHEETS_BTN: 'Data Sheets',
  QUERY_PARAMS_LABEL: 'Query Params',
  HEADERS_LABEL: 'Headers',
  EXPECTED_VALUE_PLACEHOLDER: 'Expected Value',
  BODY_JSON_LABEL: 'Full Body Payload Matching (JSON)',
  BODY_FORM_DATA_LABEL: 'Body Fields & Files Matching (JSON Object)',
  BODY_URL_ENCODED_LABEL: 'Body Fields Matching (JSON Object)',
} as const;


