export const REQUEST_SCENARIO_EDITOR_SEMANTIC_ID = {
  CONTAINER: 'request-scenario-editor-container',
  FORM: 'request-scenario-editor-form',
  HEADER: 'request-scenario-editor-header',
  TITLE: 'request-scenario-editor-title',
  BTN_CANCEL: 'request-scenario-editor-btn-cancel',
  BTN_SAVE: 'request-scenario-editor-btn-save',
  BTN_SUBMIT: 'request-scenario-editor-btn-submit',
  BASIC_CARD: 'request-scenario-editor-basic-card',
  PARAMS_CARD: 'request-scenario-editor-params-card',
  BODY_CARD: 'request-scenario-editor-body-card',
  FOOTER: 'request-scenario-editor-footer',
  INPUT_NAME: 'req-scenario-name',
  INPUT_PRIORITY: 'req-scenario-priority',
  SELECT_STRATEGY: 'req-scenario-match-strategy',
  SELECT_BODY_TYPE: 'req-scenario-body-type',
  QUERY_EDITOR: 'req-editor-query',
  HEADERS_EDITOR: 'req-editor-headers',
  BODY_EDITOR: 'req-editor-body',
  BODY_RULES_EDITOR: 'req-editor-body-rules',
} as const;
