import { ScenarioFlowExecution } from '@/src/client/domain/scenario-flow/entity/scenario_flow';
import { formatDate } from '@/src/core/utils/date';

/**
 * Generates a clean Markdown (.md) report of a Scenario Flow Execution
 */
export function generateExecutionLogMarkdown(
  execution: ScenarioFlowExecution,
  flowName?: string
): string {
  const isSuccess = execution.status === 'SUCCESS';
  const steps = execution.steps || [];
  const title = flowName || 'Scenario Flow';
  const envName = execution.environment?.name || 'Default';

  let md = `# 🧪 Test Execution Report: ${title}\n\n`;

  // Summary Metadata
  md += `| Attribute | Details |\n`;
  md += `| :--- | :--- |\n`;
  md += `| **Status** | ${isSuccess ? '✅ **PASSED**' : '❌ **FAILED**'} |\n`;
  md += `| **Execution ID** | \`${execution.id}\` |\n`;
  md += `| **Date** | ${formatDate(execution.createdAt)} |\n`;
  md += `| **Environment** | ${envName} (${execution.targetMode || 'LIVE'}) |\n`;
  md += `| **Executed By** | ${execution.executedBy || 'User'} |\n`;
  md += `| **Duration** | ${execution.durationMs || 0} ms |\n`;
  md += `| **Steps Passed** | **${execution.passedSteps || 0}** / ${execution.totalSteps || steps.length} |\n\n`;

  if (execution.errorSummary) {
    md += `> ⚠️ **Error Summary:** ${execution.errorSummary}\n\n`;
  }

  // Steps Summary Table
  md += `## 📋 Steps Overview\n\n`;
  md += `| # | Step Name | Method | Endpoint URL | Status | HTTP Code | Duration |\n`;
  md += `| :-: | :--- | :--- | :--- | :-: | :-: | :-: |\n`;

  for (const step of steps) {
    const statusIcon = step.status === 'SUCCESS' ? '✅' : step.status === 'SKIPPED' ? '⏭️' : '❌';
    const code = step.httpStatusCode ? `\`${step.httpStatusCode}\`` : '-';
    md += `| ${step.stepOrder} | ${step.stepName} | \`${step.method}\` | \`${step.url}\` | ${statusIcon} ${step.status} | ${code} | ${step.durationMs}ms |\n`;
  }

  md += `\n---\n\n`;

  // Detailed Step Breakdown
  md += `## 🔍 Step Details Breakdown\n\n`;

  for (const step of steps) {
    const statusIcon = step.status === 'SUCCESS' ? '✅ SUCCESS' : step.status === 'SKIPPED' ? '⏭️ SKIPPED' : '❌ FAILED';
    md += `### Step ${step.stepOrder}: ${step.stepName}\n\n`;
    md += `- **Endpoint**: \`${step.method} ${step.url}\`\n`;
    md += `- **Result**: ${statusIcon} (HTTP ${step.httpStatusCode || 'N/A'})\n`;
    md += `- **Execution Time**: ${step.durationMs}ms\n`;

    if (step.errorMessage) {
      md += `- **Error**: \`${step.errorMessage}\`\n`;
    }

    // Request Snapshot
    if (step.requestSnapshot) {
      const req = step.requestSnapshot as any;
      md += `\n#### 📤 Request Sent\n`;
      if (req.headers && Object.keys(req.headers).length > 0) {
        md += `**Headers:**\n\`\`\`json\n${JSON.stringify(req.headers, null, 2)}\n\`\`\`\n`;
      }
      if (req.body !== undefined && req.body !== null) {
        md += `**Body:**\n\`\`\`json\n${typeof req.body === 'object' ? JSON.stringify(req.body, null, 2) : req.body}\n\`\`\`\n`;
      }
    }

    // Response Snapshot
    if (step.responseSnapshot) {
      const resp = step.responseSnapshot as any;
      md += `\n#### 📥 Response Received\n`;
      if (resp.body !== undefined && resp.body !== null) {
        md += `\`\`\`json\n${typeof resp.body === 'object' ? JSON.stringify(resp.body, null, 2) : resp.body}\n\`\`\`\n`;
      }
    }

    // Assertions
    const assertions = (step.assertionResults as any[]) || [];
    if (assertions.length > 0) {
      md += `\n#### 🛡️ Assertions (${assertions.filter((a) => a.passed).length}/${assertions.length} passed)\n\n`;
      md += `| Rule | Operator | Expected | Actual | Result |\n`;
      md += `| :--- | :--- | :--- | :--- | :--- |\n`;
      for (const a of assertions) {
        const passIcon = a.passed ? '✅ Pass' : '❌ Fail';
        const ruleName = a.rule?.type + (a.rule?.path ? ` (${a.rule.path})` : '');
        md += `| \`${ruleName}\` | \`${a.rule?.operator}\` | \`${JSON.stringify(a.rule?.expected)}\` | \`${JSON.stringify(a.actual)}\` | ${passIcon} |\n`;
      }
    }

    // Extracted Variables
    const extracted = (step.extractedVariables as Record<string, any>) || {};
    if (Object.keys(extracted).length > 0) {
      md += `\n#### 🔑 Extracted Variables\n\n`;
      md += `| Variable | Extracted Value |\n`;
      md += `| :--- | :--- |\n`;
      for (const [k, v] of Object.entries(extracted)) {
        md += `| \`${k}\` | \`${typeof v === 'object' ? JSON.stringify(v) : v}\` |\n`;
      }
    }

    md += `\n---\n\n`;
  }

  md += `*Report automatically generated by Mock API Studio on ${new Date().toISOString()}*\n`;
  return md;
}

/**
 * Generates a clean CSV (.csv) report of a Scenario Flow Execution
 */
export function generateExecutionLogCsv(
  execution: ScenarioFlowExecution,
  _flowName?: string
): string {
  const steps = execution.steps || [];

  const headers = [
    'Step Order',
    'Step Name',
    'Method',
    'Endpoint URL',
    'Status',
    'HTTP Status Code',
    'Duration (ms)',
    'Error Message',
    'Assertions Total',
    'Assertions Passed',
    'Assertions Failed',
    'Extracted Variables',
  ];

  const escapeCsv = (val: any): string => {
    if (val === undefined || val === null) return '""';
    const str = typeof val === 'object' ? JSON.stringify(val) : String(val);
    return `"${str.replace(/"/g, '""')}"`;
  };

  const rows: string[] = [];
  rows.push(headers.map((h) => `"${h}"`).join(','));

  for (const step of steps) {
    const assertions = (step.assertionResults as any[]) || [];
    const passedAssertions = assertions.filter((a) => a.passed).length;
    const failedAssertions = assertions.length - passedAssertions;
    const extracted = step.extractedVariables ? JSON.stringify(step.extractedVariables) : '';

    const row = [
      escapeCsv(step.stepOrder),
      escapeCsv(step.stepName),
      escapeCsv(step.method),
      escapeCsv(step.url),
      escapeCsv(step.status),
      escapeCsv(step.httpStatusCode || ''),
      escapeCsv(step.durationMs || 0),
      escapeCsv(step.errorMessage || ''),
      escapeCsv(assertions.length),
      escapeCsv(passedAssertions),
      escapeCsv(failedAssertions),
      escapeCsv(extracted),
    ];

    rows.push(row.join(','));
  }

  return rows.join('\r\n');
}

/**
 * Client-side browser download helper
 */
export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * 1-Click Export to Markdown (.md)
 */
export function exportExecutionToMarkdown(
  execution: ScenarioFlowExecution,
  flowName?: string
) {
  const content = generateExecutionLogMarkdown(execution, flowName);
  const safeName = (flowName || 'scenario-flow').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const timestamp = new Date(execution.createdAt).toISOString().replace(/[:.]/g, '-');
  downloadFile(`${safeName}-execution-${timestamp}.md`, content, 'text/markdown');
}

/**
 * 1-Click Export to CSV (.csv)
 */
export function exportExecutionToCsv(
  execution: ScenarioFlowExecution,
  flowName?: string
) {
  const content = generateExecutionLogCsv(execution, flowName);
  const safeName = (flowName || 'scenario-flow').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const timestamp = new Date(execution.createdAt).toISOString().replace(/[:.]/g, '-');
  downloadFile(`${safeName}-execution-${timestamp}.csv`, content, 'text/csv');
}
