export const ROUTES = {
  SIGN_IN: '/sign-in',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  ENVIRONMENTS: '/environments',
  APIS: '/apis',
  SETTINGS: '/settings',
  FAQ: '/faq',
  ADMIN_ACCOUNTS: '/admin/accounts',
  CHANGE_LOGS: '/change-logs',
  PROJECT_DETAIL: (projectId: string) => `/projects/${projectId}`,
  PROJECT_ENVIRONMENTS: (projectId: string) => `/projects/${projectId}/environments`,
  PROJECT_APIS: (projectId: string) => `/projects/${projectId}/apis`,
  API_DETAIL: (projectId: string, apiId: string) => `/projects/${projectId}/apis/${apiId}`,
} as const;
