export const PROJECT_DETAIL_TEXT = {
  TITLE: 'Project Overview',
  SUBTITLE: 'Manage project endpoints, environment configurations, and rules.',
  BACK_TO_PROJECTS: 'Back to Projects',
  TAB_APIS: 'API Collections',
  TAB_ENVIRONMENTS: 'Environments',
  TAB_OVERVIEW: 'Project Information',
  METADATA_TITLE: 'Project Metadata',
  METADATA_PROJECT_ID: 'Project ID',
  METADATA_CREATED_AT: 'Created At',
  METADATA_LAST_UPDATED: 'Last Updated',
  CREATED_DATE_LABEL: 'Created Date',
  NO_DESCRIPTION: 'No project description configured.',
  STATUS_ACTIVE: 'Active',
  STATUS_DISABLED: 'Disabled',
  TITLE_DELETE_PROJECT: 'Delete Project',
  EXPORT_IMPORT_JSON_BTN: 'Export / Import JSON',
  OPENAPI_MODAL_TITLE: 'OpenAPI / Swagger Docs',
  OPENAPI_MODAL_DESC: (projectName: string) => `Export or Import OpenAPI 3.0 / Swagger JSON specifications specifically for ${projectName}.`,
  OPENAPI_TAB_EXPORT: 'Export OpenAPI',
  OPENAPI_TAB_IMPORT: 'Import OpenAPI',
  OPENAPI_EXPORT_FORMAT_LABEL: 'Export Format: OpenAPI 3.0.3 (JSON)',
  OPENAPI_UPLOAD_OR_PASTE_LABEL: 'Upload File or Paste OpenAPI JSON',
  OPENAPI_PLACEHOLDER_JSON: 'Paste OpenAPI / Swagger JSON spec here...',
  OPENAPI_BTN_EXPORT: 'Export OpenAPI',
  OPENAPI_BTN_IMPORT: 'Import OpenAPI',
  OPENAPI_BTN_IMPORTING: 'Importing...',
} as const;
