export const EXTERNAL_API_DOCS_SEMANTIC_ID = {
  CONTAINER: 'external-api-docs-container',
  HERO_HEADER: 'external-api-docs-hero-header',
  BTN_DOWNLOAD_OPENAPI: 'external-api-docs-download-openapi-btn',
  BTN_COPY_POSTMAN: 'external-api-docs-copy-postman-btn',
  BTN_VIEW_MARKDOWN: 'external-api-docs-view-markdown-btn',
  AUTH_BAR: 'external-api-docs-auth-bar',
  AUTH_TOKEN_INPUT: 'external-api-docs-auth-token-input',
  AUTH_TOKEN_CLEAR_BTN: 'external-api-docs-auth-token-clear-btn',
  CATEGORY_PILLS: 'external-api-docs-category-pills',
  SEARCH_INPUT: 'external-api-docs-search-input',
  ENDPOINTS_LIST: 'external-api-docs-endpoints-list',
  ENDPOINT_CARD: (id: string) => `external-api-docs-card-${id}`,
  BTN_TEST_ENDPOINT: (id: string) => `external-api-docs-test-btn-${id}`,
  PLAYGROUND_DIALOG: 'external-api-docs-playground-dialog',
  PLAYGROUND_SEND_BTN: 'external-api-docs-playground-send-btn',
  PLAYGROUND_BODY_INPUT: 'external-api-docs-playground-body-input',
  PLAYGROUND_RESPONSE_OUTPUT: 'external-api-docs-playground-response-output',
} as const;
