export const ADMIN_ACCOUNTS_TEXT = {
  TITLE: 'User Accounts',
  SUBTITLE: 'Manage system accounts, user permissions, and roles.',
  LOADING_ACCOUNTS: 'Loading user accounts...',
  NO_ACCOUNTS_TITLE: 'No Accounts Registered',
  NO_ACCOUNTS_DESC: 'There are no custom database accounts registered. Add a new account to allow multiple user roles.',
  CREATE_FIRST_BTN: 'Create First Account',
  NO_RESULTS_TITLE: 'No accounts found',
  NO_RESULTS_DESC: 'No accounts match the criteria.',
  RESET_FILTERS: 'Reset Filters',
  ADD_ACCOUNT: 'Add Account',
  EDIT_ACCOUNT: 'Edit User Account',
  ADD_USER_ACCOUNT: 'Add User Account',
  SAVE_ACCOUNT: 'Save Account',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',
  DELETE_CONFIRM_TITLE: 'Delete User Account',
  DELETE_CONFIRM_DESC: 'Are you sure you want to delete this account? This action cannot be undone.',
} as const;
