export const SETTINGS_TEXT = {
  TITLE: 'Studio Settings',
  SUBTITLE: 'Manage local database persistence, theme preferences, and backup / restore tools',
  THEME_TITLE: 'Appearance & Visual Theme',
  LIGHT_MODE: 'Light Mode',
  DARK_MODE: 'Dark Mode',
  SYSTEM_THEME: 'System Theme',
  DATABASE_TITLE: 'Database Engine & Persistence',
  DATABASE_DRIVER_LABEL: 'Database Driver',
  DATABASE_DRIVER_NAME: 'PostgreSQL Server Driver (Prisma ORM)',
  DATABASE_STATUS_LABEL: 'Engine State',
  DATABASE_STATUS_ACTIVE: 'Connected & Ready',
  DATABASE_BACKUP_SECTION: 'Backup & Restore Database',
  DATABASE_BACKUP_SECTION_DESC: 'Export native PostgreSQL SQL dumps or JSON snapshots of your mock configurations, or restore from backup files.',
  RESTRICTED_BACKUP_RESTORE_DESC: 'Backup & restore operations are restricted to Manager & Administrator roles.',

  DOWNLOAD_BACKUP_TITLE: 'Download Database Backup',
  DOWNLOAD_BACKUP_DESC: 'Export and download native PostgreSQL SQL dump (.sql) or portable JSON (.json) containing all projects, endpoints, and scenarios.',
  DOWNLOAD_BACKUP_SQL_BTN: 'Download SQL (.sql)',
  DOWNLOAD_BACKUP_JSON_BTN: 'Download JSON (.json)',
  DOWNLOAD_BACKUP_BTN: 'Download SQL Backup (.sql)',
  DOWNLOAD_BACKUP_LOADING: 'Exporting...',
  IMPORT_BACKUP_TITLE: 'Import & Restore Database',
  IMPORT_BACKUP_DESC: 'Restore or merge studio mock configurations from a SQL (.sql) dump or JSON (.json) backup file.',
  IMPORT_BACKUP_BTN: 'Import Backup File (.sql / .json)',
  IMPORT_MODAL_TITLE: 'Import Database Backup',
  IMPORT_MODAL_DESC: 'Upload a .sql or .json backup file to restore or merge your database.',
  IMPORT_DROP_LABEL: 'Click or drop a .sql or .json backup file here',
  IMPORT_SUPPORTS_LABEL: 'Supports PostgreSQL SQL dump (.sql) and JSON backups (.json)',
  IMPORT_FILE_SELECTED: 'Selected Backup File',
  IMPORT_MODE_LABEL: 'Select Import Strategy',
  IMPORT_MODE_MERGE: 'Merge Data',
  IMPORT_MODE_MERGE_DESC: 'Appends and updates records without wiping existing data',
  IMPORT_MODE_REPLACE: 'Replace All (Wipe & Restore)',
  IMPORT_MODE_REPLACE_DESC: 'Wipes all existing database records before restoring backup',
  IMPORT_REPLACE_WARNING: 'Caution: Replace mode will permanently wipe all current projects and endpoints before importing.',
  APPLY_IMPORT_BTN: 'Apply Import',
  IMPORTING_BTN: 'Restoring Database...',
  IMPORT_LOADING_TITLE: 'Restoring Database...',
  IMPORT_LOADING_DESC: 'Executing database import in chunked batches. Please do not close or refresh this page.',
  IMPORT_LOADING_BADGE: 'Batch processing database records...',
  IMPORT_SQL_LOADING_TITLE: 'Importing SQL Database...',
  IMPORT_SQL_LOADING_DESC: 'Executing SQL statements in small chunks to avoid long database transactions. Please do not close or refresh this page.',
  IMPORT_SQL_LOADING_BADGE: 'Chunking SQL statements...',
  IMPORT_CANCEL_BTN: 'Cancel',
  IMPORT_EXPORT_BTN: 'Import / Export JSON',
  DANGER_ZONE_TITLE: 'Danger Zone',
  RESET_DATABASE_TITLE: 'Wipe All Database Data',
  RESET_DATABASE_DESC: 'Permanently wipe all projects, environments, API endpoints, and response scenarios. The database will become completely empty.',
  RESET_DATABASE_BTN: 'Wipe All Data',
  RESET_DIALOG_TITLE: 'Permanently Wipe All Database Data?',
  RESET_DIALOG_DESC: 'Are you sure you want to permanently wipe all mock projects, environments, and API endpoints? This action cannot be undone and will leave the database completely empty.',
  RESET_DIALOG_CONFIRM: 'Wipe Everything',
  APP_INFO_TITLE: 'Application Information',
  APP_INFO_DESC: 'Mock API Studio is built using a clean domain architecture with Next.js 16, React 19, TypeScript, Tailwind CSS, Zustand, and PostgreSQL/Prisma persistence.',
  ONBOARDING_TITLE: 'Onboarding & Coach Marks',
  ONBOARDING_LABEL: 'Re-enable Onboarding Tour',
  ONBOARDING_DESC: 'Reset tour progress and show guide tooltips again across the application.',
  RESTART_TOUR_BTN: 'Restart Tour',
} as const;
