export const SETTINGS_SEMANTIC_ID = {
  CONTAINER: 'settings-container',
  THEME_CARD: 'settings-theme-card',
  THEME_LIGHT_BTN: 'settings-theme-light-btn',
  THEME_DARK_BTN: 'settings-theme-dark-btn',
  THEME_SYSTEM_BTN: 'settings-theme-system-btn',
  DATABASE_CARD: 'settings-database-card',
  APP_INFO_CARD: 'settings-app-info-card',
  IMPORT_EXPORT_BTN: 'settings-import-export-btn',
  DOWNLOAD_BACKUP_BTN: 'settings-download-backup-btn',
  DOWNLOAD_BACKUP_JSON_BTN: 'settings-download-backup-json-btn',
  IMPORT_BACKUP_BTN: 'settings-import-backup-btn',
  IMPORT_BACKUP_MODAL: 'settings-import-backup-modal',
  IMPORT_MODAL_CLOSE_BTN: 'settings-import-modal-close-btn',
  IMPORT_FILE_INPUT: 'settings-import-file-input',
  IMPORT_CLEAR_FILE_BTN: 'settings-import-clear-file-btn',
  APPLY_IMPORT_BTN: 'settings-apply-import-btn',
  IMPORT_CANCEL_BTN: 'settings-import-cancel-btn',
  IMPORT_MODE_MERGE_BTN: 'settings-import-mode-merge-btn',
  IMPORT_MODE_REPLACE_BTN: 'settings-import-mode-replace-btn',
  RESET_DATABASE_BTN: 'settings-reset-database-btn',
  RESTART_TOUR_BTN: 'settings-restart-tour-btn',
} as const;
