export const API_DETAIL_TEXT = {
  TITLE: 'Endpoint Details',
  SUBTITLE: 'Configure request/response scenarios, mock data, and headers.',
  TAB_SCENARIOS: 'Request & Response Scenarios',
  TAB_ENVIRONMENTS: 'Environment Overrides',
  TAB_OVERVIEW: 'Endpoint Overview',
  NOT_FOUND: 'API Endpoint Not Found',
  SIDEBAR_TITLE: 'Request Scenarios',
  SIDEBAR_ADD_BTN: 'Add',
  SIDEBAR_SEARCH_PLACEHOLDER: 'Search scenario...',
  SIDEBAR_EMPTY: 'No request scenarios matching filter',
  DETAIL_RULE_WEIGHT: 'Weight / Priority',
  DETAIL_PARAM_MATCHING: 'Query Params Matching',
  DETAIL_HEADER_MATCHING: 'Headers Matching',
  DETAIL_BODY_MATCHING: 'Body Payload Matching',
  RESPONSES_TITLE: 'Attached Response Scenarios',
  RESPONSES_ADD_BTN: 'Add Response Scenario',
  ENV_OVERRIDE_TITLE: 'Environment-based URL & Path Overrides',
  ENV_OVERRIDE_SUBTITLE: 'Test mock endpoints across different base URLs',
  OVERVIEW_PROJECT_ID: 'Project ID',
  OVERVIEW_ENDPOINT_ID: 'Endpoint ID',
  OVERVIEW_METHOD: 'HTTP Method',
  OVERVIEW_ROUTE: 'Route Path',
  OVERVIEW_CREATED: 'Created Date',
  MODAL_REQ_ADD_TITLE: 'Add Request Scenario',
  MODAL_REQ_EDIT_TITLE: 'Edit Request Scenario',
  MODAL_RESP_ADD_TITLE: 'Add Response Scenario',
  MODAL_RESP_EDIT_TITLE: 'Edit Response Scenario',
  LABEL_SCENARIO_NAME: 'Scenario Name *',
  LABEL_PRIORITY: 'Priority / Weight',
  LABEL_STATUS_CODE: 'HTTP Status Code *',
  LABEL_RESPONSE_BODY: 'JSON Response Payload *',
  LABEL_DELAY: 'Simulated Delay (ms)',
  LABEL_ACTIVE_STATUS: 'Active Status',
  BTN_CANCEL: 'Cancel',
  BTN_CREATE: 'Create Scenario',
  BTN_SAVE: 'Save Changes',
  DELETE_REQ_DIALOG_TITLE: 'Delete Request Scenario?',
  DELETE_REQ_DIALOG_DESC: 'Are you sure you want to delete this scenario and all attached response payloads?',
  DELETE_RESP_DIALOG_TITLE: 'Delete Response Scenario?',
  DELETE_RESP_DIALOG_DESC: 'Are you sure you want to delete this mock response payload?',
} as const;
